### PR TITLE
Catching errors gracefully in Liquidator & Disputer Bots

### LINKED ISSUE #1114: Catch transaction errors in liquidator and dispute bots
If the transaction fails, it shouldn't cause the script, itself, to crash. We should catch and send the error to the logger so it doesn't block other transactions from being sent.

### PR DESCRIPTION
**Pull request by nicholaspai**
Resolves #1114 

Primary focus of PR is to catch ethereum network level errors that can happen on a `function.send({from, gas, gasPrice})` but might not be caught by a `function.call(inputArgs)`--perhaps due to out of gas errors. 

I addressed this by adding a try-catch around each `.send()` call, which has the nice effect of separating application-level errors from network-level errors.

While working on this I noticed some inconsistencies in style between the Liquidator and Disputer bots:
- Liquidator does not capitalize "liquidate" in the "at" property of its Logger messages
- Disputer does not use the `Promise.all` to resolve its promises in parallel <-- I elected to make liquidator resolve promises iteratively like the disputer does, in order to better handle inventory management in which it does not have enough inventory to resolve all promises
- General clean up of Logger messages

### CODE REVIEW

File: disputer/disputer.js [hunk 1]
```diff
@@ -71,37 +73,47 @@ class Disputer {
...
           id: disputeableLiquidation.id,
-          sponsor: disputeableLiquidation.sponsor
+          sponsor: disputeableLiquidation.sponsor,
+          error: error
         });
+        continue;
+      }
 
-        Logger.debug({
+      try {
```
Comment (nicholaspai) [inline disputer/disputer.js]: If an error throws on the send, I just don't add it to the promises array

Comment (mrice32) [reply disputer/disputer.js]: Is it possible for it to error on send? Don't all (or most) async errors get thrown to the .catch() method on a the promise? And if so, won't they miss this try catch and end up being uncaught on the `await Promise.all` line?

Comment (nicholaspai) [reply disputer/disputer.js]: you're right, I added a `.catch` error handler to the `.send`, so that the Promise.all won't throw and will log the error instead

File: disputer/disputer.js [hunk 2]
```diff
@@ -71,37 +73,52 @@ class Disputer {
...
-        gasPrice: this.gasEstimator.getCurrentFastPrice()
-      });
+      disputePromises.push(
+        dispute
+          .send({
+            from: this.account,
+            gas: 1500000,
+            gasPrice: this.gasEstimator.getCurrentFastPrice()
+          })
+          .catch(error => {
```
Comment (nicholaspai) [inline disputer/disputer.js]: @mrice32 this is the new error handling via `.catch`

File: disputer/disputer.js [hunk 3]
```diff
@@ -71,37 +73,52 @@ class Disputer {
...
+            Logger.error({
+              at: "Disputer",
+              message: `Failed to dispute liquidation: ${error.message}`,
```
Comment (nicholaspai) [inline disputer/disputer.js]: I print out the error message here, since I have yet to see the actual "error" property ever getting filled out on an error

File: disputer/disputer.js [hunk 4]
```diff
@@ -71,37 +73,52 @@ class Disputer {
...
+          })
+      );
+    }
+
+    // Resolve all promises in parallel.
+    let promiseResponse = await Promise.all(disputePromises);
+
+    for (const response of promiseResponse) {
+      // response is undefined if an error is caught.
+      if (!response) {
```
Comment (nicholaspai) [inline disputer/disputer.js]: Needed to add this check here due to the `.catch` addition. If an error is caught, no response is sent

File: disputer/disputer.js [hunk 5]
```diff
@@ -143,48 +162,59 @@ class Disputer {
...
+        withdraw
+          .send({
+            from: this.account,
+            gas: 1500000,
+            gasPrice: this.gasEstimator.getCurrentFastPrice()
+          })
+          .catch(error => {
+            Logger.error({
+              at: "Disputer",
+              message: `Failed to withdraw liquidation rewards: ${error.message}`,
```
Comment (mrice32) [inline disputer/disputer.js]:
```suggestion
              message: `Failed to withdraw dispute rewards: ${error.message}`,
```

File: disputer/disputer.js [hunk 6]
```diff
@@ -71,37 +73,52 @@ class Disputer {
...
         continue;
       }
 
-      // TODO: handle transaction failures.
-      const receipt = await dispute.send({
-        from: this.account,
-        gas: 1500000,
-        gasPrice: this.gasEstimator.getCurrentFastPrice()
-      });
+      disputePromises.push(
```
Comment (mrice32) [inline disputer/disputer.js]: Does structuring it this way break the inventory management above? Let's say the both disputes cost 1 ETH and the dispute bot only has 1 ETH. Won't it try to send both transactions without realizing that one will definitely fail (because the first will spend the 1 ETH)?

File: disputer/disputer.js [hunk 7]
```diff
@@ -71,37 +73,52 @@ class Disputer {
           at: "Disputer",
           message: "Cannot dispute liquidation: not enough collateral (or large enough approval) to initiate dispute.",
           id: disputeableLiquidation.id,
-          sponsor: disputeableLiquidation.sponsor
-        });
-
-        Logger.debug({
```
Comment (mrice32) [inline disputer/disputer.js]: This debug log was specifically requested in a previous PR so that a full error message would be printed to the console for someone trying to debug.

File: liquidator/liquidator.js [hunk 8]
```diff
@@ -173,35 +190,52 @@ class Liquidator {
...
+            gasPrice: this.gasEstimator.getCurrentFastPrice()
+          })
+          .catch(error => {
+            Logger.error({
+              at: "Liquidator",
+              message: `Failed to withdraw liquidation rewards: ${error.message}`,
+              from: this.account,
+              gas: 1500000,
+              gasPrice: this.gasEstimator.getCurrentFastPrice(),
+              error
```
Comment (chrismaree) [inline liquidator/liquidator.js]: We've chatted about this in slack but do we need to put both the error message here as well as the `error.message` from above? would we not also need to key-value this pair like:
```
error:error
```

thoughts?

File: disputer/disputer.js (hunk 6 above)
Comment (nicholaspai) [reply disputer/disputer.js]: Hm this is a good point I hadn't thought of. @chrismaree why did you originally decide to call all of the liquidations in `liquidator` via `Promise.all`?

File: disputer/disputer.js (hunk 7 above)
Comment (nicholaspai) [reply disputer/disputer.js]: Are you saying we should make this a `Logger.debug` instead of a `Logger.error`? I thought Logger.error would be at least as verbose as Logger.debug

File: liquidator/liquidator.js (hunk 8 above)
Comment (nicholaspai) [reply liquidator/liquidator.js]: I've had the same issue, as mentioned to you on Slack I have never seen the `error` property get filled out, it is usually printed as `error: {}`. This is why I added the `error.message` into the message.

Regarding your second question, `error:error` and `error` are the same here, because if you just pass in a key without a value, the key gets the name of the variable, so if the variable is named `error`, the key-value will be `error:error`. I base this on empirical observation

File: disputer/disputer.js (hunk 6 above)
Comment (nicholaspai) [reply disputer/disputer.js]: Talked with Chris offline, he had not thought of this issue before. I will make both bots consistent and prefer the iterative approach where we resolve promises 1 by 1.

Comment (nicholaspai) [reply disputer/disputer.js]: Done, both liquidator and disputer resolve promises one by one

File: disputer/disputer.js (hunk 7 above)
Comment (nicholaspai) [reply disputer/disputer.js]: I added this back

Comment (mrice32) [reply disputer/disputer.js]: We can toss the entire error into the error log since that will go to the console too. I just don't want to lose the literal error message. Either way is fine with me.

Comment (nicholaspai) [reply disputer/disputer.js]: So while exploring this I realized that `Errors` don't get printed when you add them to the log, so I added this PR: https://github.com/UMAprotocol/protocol/pull/1136

File: disputer/disputer.js [hunk 9]
```diff
@@ -70,39 +57,54 @@ class Disputer {
...
+          liquidator: receipt.events.LiquidationDisputed.returnValues.liquidator,
+          id: receipt.events.LiquidationDisputed.returnValues.disputeId,
+          disputeBondPaid: receipt.events.LiquidationDisputed.returnValues.disputeBondAmount
+        };
+        Logger.info({
+          at: "Disputer",
+          message: "Dispute tx result📄",
+          disputeResult: logResult
+        });
+      } catch (error) {
```
Comment (mrice32) [inline disputer/disputer.js]: nit: maybe we should only surround the `dispute.send` with the try catch, since we probably don't want to catch other errors.

File: disputer/disputer.js [hunk 10]
```diff
@@ -128,65 +130,71 @@ class Disputer {
...
+          caller: receipt.events.LiquidationWithdrawn.returnValues.caller,
+          withdrawalAmount: receipt.events.LiquidationWithdrawn.returnValues.withdrawalAmount,
+          liquidationStatus: receipt.events.LiquidationWithdrawn.returnValues.liquidationStatus
+        };
+        Logger.info({
+          at: "Disputer",
+          message: "Withdraw tx result📄",
+          liquidationResult: logResult
+        });
+      } catch (error) {
```
Comment (mrice32) [inline disputer/disputer.js]: nit: same comment as above.

File: liquidator/liquidator.js [hunk 11]
```diff
@@ -38,81 +38,85 @@ class Liquidator {
...
+          tokensOutstanding: receipt.events.LiquidationCreated.returnValues.tokensOutstanding,
+          lockedCollateral: receipt.events.LiquidationCreated.returnValues.lockedCollateral,
+          liquidatedCollateral: receipt.events.LiquidationCreated.returnValues.liquidatedCollateral
+        };
+        Logger.info({
+          at: "Liquidator",
+          message: "Liquidation tx result 📄",
+          liquidationResult: logResult
+        });
+      } catch (error) {
```
Comment (mrice32) [inline liquidator/liquidator.js]: nit: same comment as above.

File: liquidator/liquidator.js [hunk 12]
```diff
@@ -133,77 +137,71 @@ class Liquidator {
...
+          caller: receipt.events.LiquidationWithdrawn.returnValues.caller,
+          withdrawalAmount: receipt.events.LiquidationWithdrawn.returnValues.withdrawalAmount,
+          liquidationStatus: receipt.events.LiquidationWithdrawn.returnValues.liquidationStatus
+        };
+        Logger.info({
+          at: "Liquidator",
+          message: "Withdraw tx result📄",
+          liquidationResult: logResult
+        });
+      } catch (error) {
```
Comment (mrice32) [inline liquidator/liquidator.js]: nit: same comment as above.

File: disputer/disputer.js (hunk 9 above)
Comment (nicholaspai) [reply disputer/disputer.js]: that's a great idea, will fix

Comment (nicholaspai) [reply disputer/disputer.js]: done

File: disputer/disputer.js (hunk 10 above)
Comment (nicholaspai) [reply disputer/disputer.js]: done

File: liquidator/liquidator.js (hunk 11 above)
Comment (nicholaspai) [reply liquidator/liquidator.js]: done

File: liquidator/liquidator.js (hunk 12 above)
Comment (nicholaspai) [reply liquidator/liquidator.js]: done
