### PR TITLE
fix(truffle): correct node url resolution in truffle config

### LINKED ISSUE #1888: Truffle config is broken when using INFURA_API_KEY rather than custom node
**Description**

The truffle config doesn't correctly resolve the infura url when using the INFURA_API_KEY env variable.

```
yarn truffle console --network mainnet_mnemonic
yarn run v1.22.4
$ /Users/matt/git/protocol/node_modules/.bin/truffle console --network mainnet_mnemonic
Error: The network id specified in the truffle config (1) does not match the one returned by the network (42).  Ensure that both the network and the provider are properly configured.
    at Object.detectAndSetNetworkId (/Users/matt/git/protocol/node_modules/truffle/build/webpack:/packages/environment/environment.js:97:1)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at Object.detect (/Users/matt/git/protocol/node_modules/truffle/build/webpack:/packages/environment/environment.js:24:1)
Truffle v5.1.41 (core: 5.1.41)
Node v12.18.0
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Reproduction**

1. Set `INFURA_API_KEY` in the env, but do not set `CUSTOM_NODE_URL`.
2. Run `yarn truffle console --network mainnet_mnemonic` from root.

**Expected Behavior**

Truffle should connect to the correct network.

**Additional Context**

The problem is that the `name` variable is undefined when [this line](https://github.com/UMAprotocol/protocol/blob/b3bdd88874bd67207f5d60978fd20161c42ebd23/packages/common/src/TruffleConfig.js#L39) is hit. It was previously called in the context of a function that provided the `name`.

### LINKED ISSUE #1909: yarn test shouldn't require two ganache instances
**Why**

Right now, when you run `yarn test` it requires you to have two ganache instances running -- one fork and one non-fork. This is confusing.

**How**

I think this should probably be changed so there's a separate `integration-test` (or some other) command that runs the fork tests. OR the tests should spin up their own ganache instance.

**Resolution**

The test command should require 1 or fewer ganache instances to run.

**Difficulty Score [1-10]**

4: ~2 hours

### PR DESCRIPTION
**Pull request by mrice32**
**Motivation**

This PR fixes a few issues in the truffle config:
- The nodeUrl does not correctly resolve when not using a custom node.
- Providers are not set up as functions for local networks, so they wouldn't work with scripts that are run as node processes.
- A bunch of local networks are no longer used or required (as far as I can tell).

test-fork was also moved to its own command and ci job since it requires its own ganache instance.

**Summary**

Truffle config was updated to correctly resolve the node url internally and for files that import it.

Providers are now all functions. There are no `host` and `port` fields.

Many local networks were removed.

**Issue(s)**

Fixes #1888 
Fixes #1909.

### CODE REVIEW

File: packages/common/src/TruffleConfig.js [hunk 1]
```diff
@@ -122,26 +132,23 @@ function addPublicNetwork(networks, name, networkId) {
...
 // a customOptions object.
 function addLocalNetwork(networks, name, customOptions) {
+  const nodeUrl = getNodeUrl(name);
   const defaultOptions = {
-    host: "127.0.0.1",
     network_id: "*",
-    port: 9545,
-    gas: gas
+    gas: gas,
+    provider: function(provider = nodeUrl) {
```
Comment (chrismaree) [inline packages/common/src/TruffleConfig.js:139]: this is great! this should hopefully fix the `Web3WebsocketClient` on local develop instances as well and should fix [this](https://github.com/UMAprotocol/protocol/pull/1910#discussion_r481818716) issue I was having in the serverless integration testing.

File: packages/liquidator/package.json [hunk 2]
```diff
@@ -29,7 +29,8 @@
     "/src/**/*.js"
   ],
   "scripts": {
-    "test": "truffle test && truffle test test-fork"
+    "test": "truffle test",
+    "test-fork": "truffle test test-fork --network mainnet-fork"
```
Comment (chrismaree) [inline packages/liquidator/package.json:33]: +1 for splitting these up.

File: packages/common/src/TruffleConfig.js [hunk 3]
```diff
@@ -36,7 +36,15 @@ const gasPx = 20000000000; // 20 gwei
 const gas = undefined; // Defining this as undefined (rather than leaving undefined) forces truffle estimate gas usage.
 
 // If a custom node URL is provided, use that. Otherwise use an infura websocket connection.
-const nodeUrl = customNodeUrl || `wss://${name}.infura.io/ws/v3/${infuraApiKey}`;
+function getNodeUrl(networkName = argv.network) {
+  if (isPublicNetwork(networkName) && !networkName.includes("fork")) {
+    const infuraApiKey = process.env.INFURA_API_KEY || "e34138b2db5b496ab5cc52319d2f0299";
```
Comment (chrismaree) [inline packages/common/src/TruffleConfig.js:41]: side comment: do we want to cycle to a new public key for infura? is this a common one that other projects use or where did this key come from?

**Review by chrismaree — APPROVED** [review]
This is pretty awesome. Hopefully, this fixes some issues with `Web3WebsocketClient` I was having on local test networks.
