### PR TITLE
fix(voter-dapp): display resolved admin request at index 0

### LINKED ISSUE #2020: Voter dApp doesn't decode a resolved admin request
**Description**

Screen Shot 2020-09-24 at 14 37 45

This only fails for the first Admin request.

### PR DESCRIPTION
**Pull request by nicholaspai**
Signed-off-by: Nick Pai <npai.nyc@gmail.com>

**Motivation**

#2020 

**Summary**

I'm not entirely sure why I didn't catch this previously, possibly because the resolved request at index 0 was not an admin-request.

**Issue(s)**

Fixes #2020

### CODE REVIEW

File: packages/voter-dapp/src/ResolvedRequests.js [hunk 1]
```diff
@@ -194,7 +194,7 @@ function ResolvedRequests({ votingAccount }) {
       </Typography>
       <Dialog onClose={handleCloseDialogs} open={openExplainAdminDialog}>
         <DialogTitle>Admin Proposal</DialogTitle>
-        {explainAdminDialogData && (
```
Comment (nicholaspai) [inline packages/voter-dapp/src/ResolvedRequests.js:197]: `explainAdminDialogData` is 0 for the first request

**Review by mrice32 — APPROVED** [review]
Ha, nice find!
