### PR TITLE
fix(core,affiliates): log warning to console.error, make json piping …

### LINKED ISSUE #2912: json output between affiilates process broken due to console log in core
**Description**

FindContractVersions logs a warning if you have an out of date core build. This is logged to console.log, but this breaks output for affiliates piping. Should be logged to console.error instead.

### PR DESCRIPTION
**Pull request by daywiss**
…easier to find issues

Signed-off-by: David Adams <david@umaproject.org>

**Motivation**

#2912 

**Summary**

Simply change warning log to console.error, so that it does not interfere with affiliates piping. In general warnings like this should log to error to prevent unexpected output to standard out.  Related change to affiliates pipe handler to log full output before throwing error, to ease debugging.

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [x]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [ ]  Untested

**Issue(s)**

Fixes #2912

### CODE REVIEW

**Review by nicholaspai — APPROVED** [review]

File: packages/affiliates/libs/affiliates/utils.js [hunk 1]
```diff
@@ -362,7 +362,14 @@ function makeUnixPipe(cb, stdin = process.stdin) {
         return result + str;
       })
       // once string is final, we try to parse it as json. We assume that our caller is passing us a valid json string.
-      .map(x => JSON.parse(x))
+      .map(x => {
+        try {
+          return JSON.parse(x);
+        } catch (err) {
+          console.error(x);
```
Comment (mrice32) [inline packages/affiliates/libs/affiliates/utils.js:369]: nit: why are we logging this error and rethrowing? Seems unrelated to the point of this PR and it also seems a bit strange to log the error that you're bubbling up? Won't it get printed twice?

**Review by mrice32 — APPROVED** [review]
Looks good -- one minor comment!

File: packages/affiliates/libs/affiliates/utils.js (hunk 1 above)
Comment (daywiss) [reply packages/affiliates/libs/affiliates/utils.js:369]: its actually not logging the error, its logging the object which triggered the parsing error. The reason is because the error only gives us a line within the object to refer to, but its useless without being able to actually see the object!
