### PR TITLE
Lift wrapper div outside of Step components to fix transitions

### LINKED ISSUE #638: CSSTransition seems to fail to update class name when used with withAddedContract
In Step 5, the "step step-5-enter-done" had to be hardcoded because the outer transition layer wasn't updating the className property of the top level div. This seems to happen only when wrapping the step in the higher order component, `withAddedContract`.

### PR DESCRIPTION
**Pull request by ptare**
In some cases, if the `div` element returned by `components/StepN.js`
changes entirely, then the the outer `CSSTransition` doesn't work and
results in the CSS class overrides `step-N-enter-done` never getting
applied to the div that has the CSS class `step`. This results in all of
the content having opacity 0 and being invisible.

One way to address this issue is to make sure that the direct child of
`CSSTransition` is always the same wrapper div.

Fixes #638 

Signed-off-by: Prasad Tare <prasad.tare@gmail.com>

### CODE REVIEW

File: sponsor-dapp-v2/src/components/Step1.js [hunk 1]
```diff
@@ -42,7 +42,7 @@ function Step1(props) {
   });
 
   return (
-    <div className="step step--primary">
+    <>
```
Comment (mrice32) [inline sponsor-dapp-v2/src/components/Step1.js]: Why this rather than `<div>`?

Comment (ptare) [reply sponsor-dapp-v2/src/components/Step1.js]: I think this "fragments" feature [1] is the recommended (or at least the new and shiny) way to return multiple children, rather than a wrapper div. Is there a reason why we'd prefer the div?

1. https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html

Comment (mrice32) [reply sponsor-dapp-v2/src/components/Step1.js]: SGTM - this definitely mirrors the original DOM more closely than adding a new div.
