### PR TITLE
Daily Reporter: Remove `EMPClient` dependency and event querying done outside of `EMPEventClient`

### LINKED ISSUE #1797: Reduce Daily Reporter Run-time
**Description**

yUSD Daily Report Run-time is too large and/or calls to web3 node get rate-limited. This is because yUSD has a large amount of sponsor and token holder activity compared to previously tested EMP's.

**Reproduction**

From `protocol/`, run: ` $(npm bin)/truffle exec ./reporters/index.js --network mainnet_mnemonic` using the following `.env`:

```
EMP_ADDRESS=0xb56C5f1fB93b1Fbd7c473926c87B6B9c4d0e21d5
PRICE_FEED_CONFIG={"type":"medianizer","apiKey":"xxx","lookback":7200,"invertPrice":true,"minTimeBetweenUpdates":60,"medianizedFeeds":[{"type":"cryptowatch","exchange":"coinbase-pro","pair":"ethusd"}, {"type":"cryptowatch","exchange":"binance","pair":"ethusdt"}, {"type":"cryptowatch","exchange":"kraken","pair":"ethusd"}]}
WALLET_MONITOR_OBJECT=[]
```

**Expected Behavior**

Global Summary Stats should fail to print

**Screenshots**

Screen Shot 2020-08-03 at 12 55 04

**Version and OS Info**

 - OS: macOS Catalina (10.15.5)
 - Browser: N/A (CLI, zsh)
 - Version `f1fc2b3b`

**Additional Context**

### PR DESCRIPTION
**Pull request by nicholaspai**
Signed-off-by: Nick Pai <npai.nyc@gmail.com>

**Motivation**

#1797

**Summary**

I removed all the `EMPClient` dependency as well as any event querying outside of the `EMPEventClient`.

Runtime decreased from >35 seconds to 5 seconds mostly because we no longer need to call `empClient.update()`

IMPORTANTLY: This temporarily will remove all period-specific data for `summary stats` such as Collateral Deposited for a period (and delta vs previous period). This is because the summary cash flows cannot be sub-divided currently by the UMA subgraph. 

**Details**

- To calculate synthetic token holder count, previously was going through all `Transfer` events and constructing a token holder list. I removed the `Transfer`-event fetching as this was running into our web3 node's rate-limiting. Instead, use [ethplorer.io](https://github.com/EverexIO/Ethplorer/wiki/Ethplorer-API) to query tokenholder count. The benefit is speed, while the downside is reliance on a third party and we can no longer query token holder stats "per period". Infura rate-limiting was referenced as potential future technical debt [here](https://github.com/UMAprotocol/protocol/pull/1575#discussion_r435943818). We have hit the limit 😅.

- Instead of using `Transfer` events to compute `totalCollateralDeposited`, `totalCollateralWithdrawn`, and `totalSyntheticBurned`, I query these values directly from the UMA subgraph. The upside here is speed, while the downside is again reliance on a third party and also no longer being able to segment these stats "per period"

- I removed all dependency on the `empClient`, as calling `empClient.update()` took > 30 seconds. I can grab `lastUpdateTimestamp` from the `empEventClient` instead and I can get the # of current active positions via the UMA subgraph. 

**Issue(s)**

Fixes #1797

### CODE REVIEW

**Comment by nicholaspai** [comment]
> This is sweet!
> 
> Quick question: what is the cloud run timeout? I thought it was something like 15 minutes? Why is a 35 -> 5 second reduction fixing the timeout? Side note: regardless, I think this PR makes sense. I'm just surprised that the timeout is so low -- I would expect that small of a timeout to break our other bots if they were to run on cloud run.
> 
> EDIT: Apparently the default timeout is 5 minutes (still >> 35 seconds). Apparently this is configurable, though.
> 
> cc @chrismaree also might have some thoughts here.

I don't think the timeout is the issue, I think its the amount of requests to Infura to process all `Transfer` events for the the synthetic and collateral currencies

**Comment by chrismaree** [comment]
> This is sweet!
> 
> Quick question: what is the cloud run timeout? I thought it was something like 15 minutes? Why is a 35 -> 5 second reduction fixing the timeout? Side note: regardless, I think this PR makes sense. I'm just surprised that the timeout is so low -- I would expect that small of a timeout to break our other bots if they were to run on cloud run.
> 
> EDIT: Apparently the default timeout is 5 minutes (still >> 35 seconds). Apparently this is configurable, though.
> 
> cc @chrismaree also might have some thoughts here.

Actually we have the timeout set to 900 seconds (15 mins). But like @nicholaspai said I think the reason it failed is due to wild queries and very high load. It looks like the container actually runs out of memory (2gb cap) and then crashes on this reporter.

This refactor should 100% help with these issues :)

File: reporters/graphql/umaSubgraph.js [hunk 1]
```diff
@@ -35,13 +39,17 @@ function LIQUIDATION_EVENTS_FOR_EMP(empAddress) {
             }
           }
         }
+        totalCollateralDeposited
```
Comment (chrismaree) [inline reporters/graphql/umaSubgraph.js:42]: wow this is great! such a simple query returns so much data. great work @nicholaspai

Comment (nicholaspai) [reply reporters/graphql/umaSubgraph.js:42]: downside is we have no idea how its calculated but it seems correct!
