### PR TITLE
fix(liquidator,disputer & monitor bot): error exit with non-zero error code

### LINKED ISSUE #1919: Bots exit with error return 0 exit code
**Description**

If a bot crashes it should always return a non-zero error code to indicate an error has occurred. Even if the bot has crashed as a result of a try-catch process and the error has been logged it should still yield with a non-zero error code. 

This is important in configuring Docker containers to re-boot on error as well as to build serverless execution that needs to know if the process has crashed.

The current bot implementation (liquidator, disputer, and monitor) does not always return a non-zero error code on a crash. This is due to the `catch` logic in the main `run` try-catch block [here](https://github.com/UMAprotocol/protocol/blob/3dbd730d7407b182069d5e7c4c8e7b8061360d77/packages/liquidator/index.js#L208) not throwing or exiting the process. As a result, an error is caught, logged and then the process returns the main `run` function to the `Poll` function with no error. After returning, the `Poll` function calls the bots callback [here](https://github.com/UMAprotocol/protocol/blob/3dbd730d7407b182069d5e7c4c8e7b8061360d77/packages/liquidator/index.js#L279) with no error present. As a result, the bot exits with no error status, even though there was an error in the execution.

**Reproduction**

Run any of the bots and generate an execution error in them. You'll see them log the error then exit with a zero exit code. Alternatively, run a docker instance of the bots and generate an error. Again you'll see when they crash they don't report it as a failed process

**Expected Behavior**

If a process crashes it should always return a non-zero exit code to indicate their was an error.

### PR DESCRIPTION
**Pull request by chrismaree**
**Motivation**

When the bots process exits with error it does not always return a non-zero error code. This is unintended behavior. The implication of this is that a crashed bot does not re-boot it's Docker container and logging on the process level is not always correct. For more details see issue [1919](https://github.com/UMAprotocol/protocol/issues/1919).

**Summary**

To fix this the main `run` function now throws an error if it fails in the try-catch block. Previously this catch simply logged the error and returned. The tests were also updated accordingly.

**Issue(s)**

Fixes #1919

### CODE REVIEW

File: packages/disputer/index.js [hunk 1]
```diff
@@ -155,12 +155,8 @@ async function run(
...
     }
   } catch (error) {
-    logger.error({
-      at: "Disputer#index",
-      message: "Disputer polling error🚨",
-      error: typeof error === "string" ? new Error(error) : error
-    });
-    await waitForLogger(logger);
+    // If any error is thrown, catch it and bubble up to the main try-catch for error processing in the Poll function.
+    throw typeof error === "string" ? new Error(error) : error;
```
Comment (daywiss) [inline packages/disputer/index.js:159]: im not sure where in the code strings are thrown as errors, but this check is really weird to me.  worth pointing out that with nodes `assert` you can easily generate descriptive errors with less code.

Comment (chrismaree) [reply packages/disputer/index.js:159]: Ye, it is a bit janky and strange. We do this in a few places as sometimes there are errors generated by upstream components that come out as strings. Specifically, web3.js can sometimes make errors that are not consistent in type, such as WebSocket errors. Ideally, We should refactor this to be cleaner and more consistent but for now, we've found this to be the most robust way to catch these kinds of issues.
