### PR TITLE
Stacktrace winston formatter

### LINKED ISSUE #1515: Bots errors should show stack traces
Right now bot stack traces are not very informative. This should be fixed.

### PR DESCRIPTION
**Pull request by chrismaree**
This PR adds a formatter to print error stack traces to Winston logs. Before log messages in slack looked as follows for an invalid function `updatez` within the `empEventClient`:
image

This message is useful but a stack trace would really help with debugging. After this PR error messages look as follows:
image

close #1515

### CODE REVIEW

File: monitors/SyntheticPegMonitor.js [hunk 1]
```diff
@@ -85,7 +85,7 @@ class SyntheticPegMonitor {
     const deviationError = this._calculateDeviationError(uniswapTokenPrice, cryptoWatchTokenPrice);
     // If the percentage error is greater than (gt) the threshold send a message.
     if (deviationError.gt(this.web3.utils.toBN(this.deviationAlertThreshold))) {
-      this.logger.error({
+      this.logger.warn({
```
Comment (chrismaree) [inline monitors/SyntheticPegMonitor.js:88]: I changed this from `error` to `warn` as `error` should be reserved for application errors only. these log messages will still fire Pagerduty alerts but wont be tagged as an error.

File: financial-templates-lib/logger/Logger.js [hunk 2]
```diff
@@ -33,23 +33,32 @@ const { transports } = require("./Transports");
 // This async function can be called by a bot if the log message is generated right before the process terminates.
 // By calling `await waitForLogger(Logger)`, with the local Logger instance, the process will wait for all upstream
 // transports to clear. This enables slower transports like slack to still send their messages before the process yields.
-async function waitForLogger(logger) {
+const waitForLogger = async logger => {
```
Comment (chrismaree) [inline financial-templates-lib/logger/Logger.js:36]: Refactored formatting to be consistent

File: financial-templates-lib/logger/Logger.js [hunk 3]
```diff
@@ -33,23 +33,32 @@ const { transports } = require("./Transports");
...
+const errorStackTracerFormatter = logEntry => {
+  if (logEntry.error) {
+    logEntry.error = logEntry.error.stack;
+  }
+  return logEntry;
+};
 
 // This formatter checks if the `BOT_IDENTIFIER` env variable is present. If it is, the name is appended to the message.
-const winstonFormatter = logEntry => {
+const botIdentifyFormatter = logEntry => {
```
Comment (chrismaree) [inline financial-templates-lib/logger/Logger.js:51]: renamed to be consistent

File: financial-templates-lib/price-feed/CryptoWatchPriceFeed.js [hunk 4]
```diff
@@ -101,7 +101,11 @@ class CryptoWatchPriceFeed extends PriceFeedInterface {
 
     const ohlcResponse = await this.networker.getJson(ohlcUrl);
     if (!ohlcResponse || !ohlcResponse.result || !ohlcResponse.result[this.ohlcPeriod]) {
-      console.error("Could not parse ohlc result:", ohlcResponse);
+      this.logger.error({
```
Comment (chrismaree) [inline financial-templates-lib/price-feed/CryptoWatchPriceFeed.js:104]: This implementation was using `console.error`. I updated this to be consistent.

File: monitors/SyntheticPegMonitor.js (hunk 1 above)
Comment (mrice32) [reply monitors/SyntheticPegMonitor.js:88]: Agreed on these -- only one that we might want to keep as an error is the peg price volatility alert, since that one doesn't depend on the synthetic price and may signal a true time of stress for the market. Thoughts? Not super opinionated either way.

Comment (chrismaree) [reply monitors/SyntheticPegMonitor.js:88]: Is that an error though? it's more of a warning than anything else in my mind. I'd favor consistency imho but am happy to change this if you want.

Comment (mrice32) [reply monitors/SyntheticPegMonitor.js:88]: SGTM, fine with keeping as is.
