### PR TITLE
fix(serverless-spoke) Add waitForLogger to process termination

### LINKED ISSUE #2022: Improve serverless logging flakeyness by waiting for slow transports
**Why**

Some transports can be slow, such as the slack transport. in the case where a process is yielding (due to an error or end of loop) sometimes these slow transports are not yet finished reporting their messages and the bot can exit before logging. this can result in lots not propagating to the respective transport.

**How**

Add the `waitForLogger()` method to the hub and spoke.

**Resolution**

Logs are consistently delivered.

**Difficulty Score [1-10]**

- 3: ~1 hour

### PR DESCRIPTION
**Pull request by chrismaree**
**Motivation**

issue #2022 

**Summary**

Some transports can be slow, such as the slack transport. in the case where a process is yielding (due to an error or end of loop) sometimes these slow transports are not yet finished reporting their messages and the bot can exit before logging. this can result in lots not propagating to the respective transport. 

This PR adds the `waitForLogger` syntax to the spoke.

**Issue(s)**

close #2022

### CODE REVIEW

File: packages/financial-templates-lib/src/logger/Logger.js [hunk 1]
```diff
@@ -33,10 +33,14 @@ const { transports } = require("./Transports");
 // This async function can be called by a bot if the log message is generated right before the process terminates.
 // By calling `await waitForLogger(Logger)`, with the local Logger instance, the process will wait for all upstream
 // transports to clear. This enables slower transports like slack to still send their messages before the process yields.
+// Note that if running in tests we dont want to yield the logger so check if there is a `test` in the process args.
 async function waitForLogger(logger) {
-  const loggerDone = new Promise(resolve => logger.on("finish", resolve));
-  logger.end();
-  return await loggerDone;
+  if (require("minimist")(process.argv.slice(), {})._.indexOf("test") == -1) {
```
Comment (daywiss) [inline packages/financial-templates-lib/src/logger/Logger.js:38]: i think this would be a lot cleaner if the application controlled its usage of this through a config. For instance parsing an env to like `isTest` in ServerlessSpoke, and then like `!isTest&& await waitForLogger(logger)`.  Or alternatively allow a default parameter `await waitForLogger(logger,isTest)` which bypasses the wait if true

File: packages/core/scripts/serverless-orchestration/ServerlessSpoke.js [hunk 2]
```diff
@@ -55,7 +55,7 @@ spoke.post("/", async (req, res) => {
       childProcessIdentifier: _getChildProcessIdentifier(req),
       execResponse
     });
-
+    waitForLogger(logger);
```
Comment (daywiss) [inline packages/core/scripts/serverless-orchestration/ServerlessSpoke.js:58]: these probably need to be awaited

**Comment by chrismaree** [comment]
Update: this PR has bee refined to simply use a short 2-second delay before terminating the hub and spoke processes.

**Review by daywiss — COMMENTED** [review]
Hopefully this fixes the issue but may want to parameterize the delay time in case we still see problems at 2 seconds -- unless you think this is more than enough time. 

Also I know this is kind of dirty so maybe we just keep an issue open to refactor this, idk i feel like there is a proper solution to this but wouldn't want you to have to spend more time on it if this is good enough. WDYT?

**Comment by daywiss** [comment]
Looking into winston a bit, there is a way to wait for a flush to complete. I think this might be better of being handled in the winston context. We can save this for a new PR but:

> Awaiting logs to be written in winston
> Often it is useful to wait for your logs to be written before exiting the process. Each instance of winston.Logger is also a [Node.js stream]. A finish event will be raised when all logs have flushed to all transports after the stream has been ended.
> 
> const transport = new winston.transports.Console();
> const logger = winston.createLogger({
>   transports: [transport]
> });
> 
> logger.on('finish', function (info) {
>   // All `info` log messages has now been logged
> });
> 
> logger.info('CHILL WINSTON!', { seriously: true });
> logger.end();

So you could add a process exit handler file which does something like this:
```js
process.on('exit', processExitHandler)
process.on('uncaughtException', processExitHandler) 
process.on('unhandledRejection', processExitHandler)

// then stop winston logs
function processExitHandler(){
  logger.on('finish',()=>process.exit())
  logger.end()
}
```

**Review by mrice32 — APPROVED** [review]
LGTM!

**Comment by chrismaree** [comment]
> Looking into winston a bit, there is a way to wait for a flush to complete. I think this might be better of being handled in the winston context. We can save this for a new PR but:
> 
> > Awaiting logs to be written in winston
> > Often it is useful to wait for your logs to be written before exiting the process. Each instance of winston.Logger is also a [Node.js stream]. A finish event will be raised when all logs have flushed to all transports after the stream has been ended.
> > const transport = new winston.transports.Console();
> > const logger = winston.createLogger({
> > transports: [transport]
> > });
> > logger.on('finish', function (info) {
> > // All `info` log messages has now been logged
> > });
> > logger.info('CHILL WINSTON!', { seriously: true });
> > logger.end();
> 
> So you could add a process exit handler file which does something like this:
> 
> ```js
> process.on('exit', processExitHandler)
> process.on('uncaughtException', processExitHandler) 
> process.on('unhandledRejection', processExitHandler)
> 
> // then stop winston logs
> function processExitHandler(){
>   logger.on('finish',()=>process.exit())
>   logger.end()
> }
> ```

thanks for this @david. This is in fact the exact logic that the `waitForLogger` module uses. You can check it out over here: https://github.com/UMAprotocol/protocol/blob/8e1b1898c153bd6b48559226400caed0b49a1a46/packages/financial-templates-lib/src/logger/Logger.js#L36

This works super well if the intention is to _close_ or end the node process after the logs are sent. All the bots use this at the end of their execution loops: the bot is finished sending running and is exiting and we want to be sure that Winston has flushed it's transports before the process yields. For example you can see it used here in the liquidator bot:
https://github.com/UMAprotocol/protocol/blob/8e1b1898c153bd6b48559226400caed0b49a1a46/packages/liquidator/index.js#L304

The reason this **does not work in serverless** is that we don't actually want to end the logger (or the node process) after the hub or spoke returns. We want to keep the process & transport open for future queries. `waitforLogger` (and the logic in your comment) are only useful if you ending the node process.

Unfortunately, Winston only emits the `finish` event iff the process has been exited. What we really need is the ability to "wait for transports to flush" without having to kill the Winston process. From my experimentation and research, this is not possible (at least without having to modify winston).

**Comment by daywiss** [comment]
> The reason this does not work in serverless is that we don't actually want to end the logger (or the node process) after the hub or spoke returns. We want to keep the process & transport open for future queries. waitforLogger (and the logic in your comment) are only useful if you ending the node process.

I see... thanks for that explanation. Yea you cant really know when send is done without explicitly ending the stream.

**Review by daywiss — APPROVED** [review]
