### PR TITLE
fix(emp-contract): LiquidationWithdrawn settlementPrice emitted correctly.

### LINKED ISSUE #1911: LiquidationWithdrawn event's `settlementPrice` sometimes unexpected
**Description**

The `LiquidationWithdrawn` event attempts to emit the `settlementPrice`, which is the resolved price relevant to a disputed liquidation, if a liquidation was disputed. However, once all rewards have been withdrawn, the `settlementPrice`, along with the entire `liquidation` struct is deleted. So, we cannot pull `settlementPrice` from `liquidation`, but instead need to store an intermediate value. This is the [offending code](https://github.com/UMAprotocol/protocol/blob/master/packages/core/contracts/financial-templates/expiring-multiparty/Liquidatable.sol#L479)

**Reproduction**

Dispute a liquidation in which the disputer, liquidator, and sponsor are same account. Withdrawing rewards therefore deletes the struct and emits a `LiquidationWithdrawn` event with an unexpected `settlementPrice` of 0.

**Expected Behavior**

The `settlementPrice` should be equal to the resolved price, even if the `withdrawLiquidation()` call deletes the `liquidation` struct.

**Screenshots**

[Example Kovan event emitting 0 as the settlement price](https://kovan.etherscan.io/tx/0x4056bd026f74328000a80ca14275158051d9b36741f9f46430be04f0bcb97650#eventlog)

You can see prior to this event that the dispute's price request settled to a non 0 value.

### PR DESCRIPTION
**Pull request by nicholaspai**
Signed-off-by: Nick Pai <npai.nyc@gmail.com>

**Motivation**

#1911 

**Summary**

Store `settlementPrice` in intermediate var.

**Issue(s)**

Fixes #1911

### CODE REVIEW

File: packages/core/test/financial-templates/Liquidatable.js [hunk 1]
```diff
@@ -1542,7 +1542,7 @@ contract("Liquidatable", function(accounts) {
           // State should be uninitialized as the struct has been deleted as a result of the withdrawal.
           // Once a dispute fails and the liquidator withdraws the struct is removed from state.
           ev.liquidationStatus.toString() == LiquidationStatesEnum.UNINITIALIZED &&
-          ev.settlementPrice.toString() == "0"
```
Comment (daywiss) [inline packages/core/test/financial-templates/Liquidatable.js:1545]: oh were these cases where the value was empty before

Comment (nicholaspai) [reply packages/core/test/financial-templates/Liquidatable.js:1545]: Not empty but 0 because the struct was deleted. These tests were therefore false positives because we fixed the the RHS of the assert.equal to match the (unexpected) 0 price

**Comment by mrice32** [comment]
@nicholaspai don't forget to request reviewers!

File: packages/core/test/financial-templates/Liquidatable.js (hunk 1 above)
Comment (kendricktan) [reply packages/core/test/financial-templates/Liquidatable.js:1545]: These should be using JavaScript triple equals

Comment (nicholaspai) [reply packages/core/test/financial-templates/Liquidatable.js:1545]: Yeah they all should good catch
