### PR TITLE
fix(optimistic-oracle): add future time require to optimistic oracle

### LINKED ISSUE #2266: Optimistic oracle should not allow future requests
**Description**

If the optimistic oracle allows future requests, it can create situations where the DVM won't allow a valid dispute to be placed.

**Expected Behavior**

Optimistic oracle should not allow future requests, as the DVM does.

### PR DESCRIPTION
**Pull request by mrice32**
**Motivation**

#2266.

**Summary**

Limit optimistic oracle requests to right now or the past. No future requests should be allowed.

**Issue(s)**
Fixes #2266

### CODE REVIEW

File: packages/core/test/oracle/OptimisticOracle.js [hunk 1]
```diff
@@ -122,6 +122,20 @@ contract("OptimisticOracle", function(accounts) {
     await verifyState(OptimisticOracleRequestStatesEnum.INVALID);
   });
 
+  it("Future request", async function() {
```
Comment (nicholaspai) [inline packages/core/test/oracle/OptimisticOracle.js:125]:
```suggestion
  it("Request timestamp in the future", async function() {
```

File: packages/core/contracts/oracle/implementation/OptimisticOracle.sol [hunk 2]
```diff
@@ -156,6 +156,7 @@ contract OptimisticOracle is OptimisticOracleInterface, Testable, Lockable {
         require(getState(msg.sender, identifier, timestamp, ancillaryData) == State.Invalid, "requestPrice: Invalid");
         require(_getIdentifierWhitelist().isIdentifierSupported(identifier), "Unsupported identifier");
         require(_getCollateralWhitelist().isOnWhitelist(address(currency)), "Unsupported currency");
+        require(timestamp <= getCurrentTime().add(90), "Timestamp in future"); // Give 90 seconds of leeway.
```
Comment (nicholaspai) [inline packages/core/contracts/oracle/implementation/OptimisticOracle.sol:159]: I think this deserves a comment or some more explanation why this just can't be `timestamp <= getCurrentTime()`. Just explaining the situation where `timestamp > currentTime`

Comment (mrice32) [reply packages/core/contracts/oracle/implementation/OptimisticOracle.sol]: As discussed offline, we can just get rid of the 90 second window.

File: packages/core/contracts/oracle/implementation/OptimisticOracle.sol [hunk 3]
```diff
@@ -156,6 +156,7 @@ contract OptimisticOracle is OptimisticOracleInterface, Testable, Lockable {
         require(getState(msg.sender, identifier, timestamp, ancillaryData) == State.Invalid, "requestPrice: Invalid");
         require(_getIdentifierWhitelist().isIdentifierSupported(identifier), "Unsupported identifier");
         require(_getCollateralWhitelist().isOnWhitelist(address(currency)), "Unsupported currency");
+        require(timestamp <= getCurrentTime(), "Timestamp in future"); // Give 90 seconds of leeway.
```
Comment (nicholaspai) [inline packages/core/contracts/oracle/implementation/OptimisticOracle.sol:159]:
```suggestion
        require(timestamp <= getCurrentTime(), "Timestamp in future");
```

**Review by nicholaspai — APPROVED** [review]
LGTM! Nit to remove a comment

**Comment by mrice32** [comment]
> LGTM! Nit to remove a comment

Ahh, nice catch. Thanks
