### PR TITLE
fix(affiliates): when getting balances use all time logs instead of logs from start time

### LINKED ISSUE #2173: EMP balances need different start time than specified reward period
This was an oversight, but in order to calculate balances correctly, we need all events from the start of the emp contract. Currently the script uses the start time provided by the user, which may be well after EMP was deployed. 

Script needs to correctly deduce start of emp, and use that as the start time for events to calculate user balances even if reward period starts well after that.

### PR DESCRIPTION
**Pull request by daywiss**
**Motivation**
#2173 

**Summary**
Previously when running script for some time frames, it would fail with incorrect or negative balances. This is because we need to generate balances from start of each emp deployment. 

This fix allows us to run deployer rewards for any time period that does not encompass the emp creation time. This brute forces the query from bigquery, it has to search through all time to get these logs and costs about 25 cents per contract.

- gets balances and emp deployer events for all time vs respecting user start time. We need balances to generate from all time, but user may specify a start time that does not meet this requirement.
- fixes bug when handling events that call settle expired. apparently users without positions can call this.

**Issue(s)**

Fixes #2173, #2170

### CODE REVIEW

File: packages/affiliates/libs/affiliates.js [hunk 1]
```diff
@@ -16,9 +16,11 @@ const DeployerRewards = ({ queries, empCreatorAbi, empAbi, coingecko, synthPrice
   assert(empAbi, "requires empAbi");
   assert(coingecko, "requires coingecko api");
   assert(synthPrices, "requires synthPrices api");
-  async function getBalanceHistory(address, start, end) {
+  async function getBalanceHistory(address) {
     // stream is a bit more optimal than waiting for entire query to return as array
-    const stream = await queries.streamLogsByContract(address, start, end);
+    // We need all logs from beginning of time. This could be optimized by deducing or supplying
+    // the specific emp start time to narrow down the query.
+    const stream = await queries.streamAllLogsByContract(address);
```
Comment (daywiss) [inline packages/affiliates/libs/affiliates.js:23]: This is the main logical change here, events to generate balances are queried for all time ( to get all contract events) vs previously used start and end time.

File: packages/affiliates/libs/affiliates.js [hunk 2]
```diff
@@ -66,14 +68,19 @@ const DeployerRewards = ({ queries, empCreatorAbi, empAbi, coingecko, synthPrice
...
-    return logs.map(decode).reduce((result, log) => {
-      result.push([log.args.expiringMultiPartyAddress, log.args.deployerAddress]);
-      return result;
-    }, []);
+    return logs
+      .map(log => decode(log, log))
+      .reduce((result, log) => {
+        result.push([
+          log.args.expiringMultiPartyAddress,
+          { deployer: log.args.deployerAddress, timestamp: log.block_timestamp, number: log.block_number }
```
Comment (daywiss) [inline packages/affiliates/libs/affiliates.js:80]: this just adds additional meta data as we processs the deployer logs. Could be used to optimize balance queries by getting deployment time for each emp contract. Currently though its not used.

File: packages/affiliates/libs/affiliates.js [hunk 3]
```diff
@@ -203,17 +209,19 @@ const DeployerRewards = ({ queries, empCreatorAbi, empAbi, coingecko, synthPrice
...
-    const syntheticTokenPrices = await Promise.map(
-      empWhitelist,
-      async address => await getSyntheticPriceHistory(address, startTime, endTime)
-    );
-    const blocks = await getBlocks(startTime, endTime);
-    const balanceHistories = await getAllBalanceHistories(empWhitelist, startTime, endTime);
-    const empDeployers = await getEmpDeployerHistory(empCreatorAddress, startTime, endTime);
+    // query all required data ahead of calcuation
+    const [collateralTokenPrices, syntheticTokenPrices, blocks, empDeployers, balanceHistories] = await Promise.all([
+      Promise.map(
```
Comment (daywiss) [inline packages/affiliates/libs/affiliates.js:214]: small optimization to wrap these awaits in promise.all

File: packages/affiliates/libs/bigquery.js [hunk 4]
```diff
@@ -8,7 +8,21 @@ module.exports = ({ client } = {}) => {
 
   // types of queries we are interested in
   const queries = {
-    // logs aka events by contract
+    // this is an expensive call (50gb at time of writing), but is necessary to get all logs without knowing
+    // the deployment time of a contract.
+    allLogsByContract(contract, selection = ["*"]) {
```
Comment (daywiss) [inline packages/affiliates/libs/bigquery.js:13]: added another bigquery function to get logs without a date range, vs logsByContract which you specify start and end time

File: packages/affiliates/libs/datasets.js [hunk 5]
```diff
@@ -133,6 +133,17 @@ function Dataset(basePath, { queries, coingecko, synthPrices }) {
         .on("close", res);
     });
   }
+  function allLogs({ contract, select }, path) {
```
Comment (daywiss) [inline packages/affiliates/libs/datasets.js:136]: update dataset generation as well to use all time event logs

File: packages/affiliates/libs/datasets.js [hunk 6]
```diff
@@ -257,6 +271,14 @@ function MockQueries(basePath) {
...
       .toPromise(Promise);
   }
+  function getAllLogsByContract(address) {
+    return streamLogsByContract(address)
+      .collect()
+      .toPromise(Promise);
+  }
+  function streamAllLogsByContract(address) {
+    return streamLogsByContract(address);
+  }
```
Comment (daywiss) [inline packages/affiliates/libs/datasets.js:281]: adds in mock functions to mimick the bigquery library

File: packages/affiliates/libs/processors.js [hunk 7]
```diff
@@ -147,9 +147,23 @@ function EmpBalances(handlers = {}, { collateral, tokens } = {}) {
...
+          // ignore balance below 0 error
+        }
+      }
+      if (tokens.has(caller)) {
+        try {
+          tokens.sub(caller, tokensBurned.toString());
+        } catch (err) {
+          // ignore balance below 0 error
+        }
+      }
```
Comment (daywiss) [inline packages/affiliates/libs/processors.js:166]: convoluted logic, but when emps expire anyone without a position can settle. This was causing balances to go negative and throw errors. So now we just swallow the error, though maybe this could be done better.

File: packages/affiliates/libs/affiliates.js (hunk 1 above)
Comment (nicholaspai) [reply packages/affiliates/libs/affiliates.js:23]: Is there any reason why you can't manually set an end time, even if you must now default start time to deployment time?

Comment (daywiss) [reply packages/affiliates/libs/affiliates.js:23]: Could definitely be done that way, and I would consider that as an improvement/optimization to this. Really just wanted to get a fix in quickly without too much additional complexity though, because getting the start time of each emp was a bit ugly.

[made an issue for your suggestion](https://github.com/UMAprotocol/protocol/projects/6#card-49245181)

**Review by nicholaspai — APPROVED** [review]
This makes sense, but why can't you specify end date? As long as you default start date to deployment time I think it should be OK.

File: packages/affiliates/libs/affiliates.js (hunk 1 above)
Comment (nicholaspai) [reply packages/affiliates/libs/affiliates.js:23]: Got it, yeah you can always add it later if you need it.

**Comment by daywiss** [comment]
> This makes sense, but why can't you specify end date? As long as you default start date to deployment time I think it should be OK.

I can specify end date, i just didn't want to add a weird function where it was not taking a start date but taking an end date for the query. But i can imitate this by reusing the function which takes start/end and specify start time as something small. I will make that change.

File: packages/affiliates/libs/processors.js (hunk 7 above)
Comment (mrice32) [reply packages/affiliates/libs/processors.js:166]: Hmmm, interesting case. Have you thought about querying only blocks _up to_ expiry? Have we decided whether to include expired contracts in developer mining?

File: packages/affiliates/scripts/example-balances.js [hunk 8]
```diff
@@ -1,26 +1,27 @@
...
-const start = moment("2020-9-20", "YYYY-MM-DD").valueOf();
-const end = moment("2020-10-10", "YYYY-MM-DD").valueOf();
+const { getAbi } = require("@uma/core");
+const { EmpBalancesHistory, EmpBalances } = require("../libs/processors");
+
+const abi = getAbi("ExpiringMultiParty");
+// sanity check various contracts
+// const empContract = "0x3605Ec11BA7bD208501cbb24cd890bC58D2dbA56";
+// const empContract = "0xaBBee9fC7a882499162323EEB7BF6614193312e3"
+// const empContract =   "0x3605Ec11BA7bD208501cbb24cd890bC58D2dbA56"
```
Comment (mrice32) [inline packages/affiliates/scripts/example-balances.js:12]: nit: did you mean to leave this comment here? If so, maybe we should label the different addresses for clarity?

File: packages/affiliates/libs/affiliates.js [hunk 9]
```diff
@@ -66,14 +68,19 @@ const DeployerRewards = ({ queries, empCreatorAbi, empAbi, coingecko, synthPrice
   }
 
   // returns array of tuples [emp address, deployer address]
-  async function getEmpDeployerHistory(address, start, end) {
-    // this query is relatively small
-    const logs = await queries.getLogsByContract(address, start, end);
+  async function getEmpDeployerHistory(address) {
+    // this query is relatively small but expensive, gets all logs from begginning of time
+    const logs = await queries.getAllLogsByContract(address);
```
[the remark this answers is not in the document]
Comment (daywiss) [reply packages/affiliates/libs/affiliates.js:73]: about 25 cents per contract, 50+ gb.

File: packages/affiliates/libs/processors.js (hunk 7 above)
Comment (daywiss) [reply packages/affiliates/libs/processors.js:166]: > Have you thought about querying only blocks up to expiry?

I have not.  Would be a bit more complicated to handle that though.

> Have we decided whether to include expired contracts in developer mining?

Theres been no decision around that, the calculation currently has no notion of an expired contract so it will continue to weight them for rewards.  That is something we should probably figure out though!

**Review by chrismaree — APPROVED** [review]
