### PR TITLE
Patched Voter dApp to work w/ updated subgraph

### LINKED ISSUE #1769: Voterdapp stat issue
If logged into a wallet that _did not vote_ the dapp shows an error rather than no vote commited.
image

Also, clicking on display stats does not work, properly due to the same error in the console
image

### PR DESCRIPTION
**Pull request by nicholaspai**
UMA subgraph interface changed:
- `commitedVotes` now `committedVotes`
-  Round`claimedPercentage` no longer a prop but also no longer necessary since `inflationRate` is available.

Big add here is that we can use the round's queried `inflationRate` and avoid making contract calls in the VoteData container.

Resolves #1769 
Signed-off-by: Nick Pai <npai.nyc@gmail.com>

### CODE REVIEW

File: voter-dapp/src/ResolvedRequests.js [hunk 1]
```diff
@@ -138,6 +138,13 @@ function ResolvedRequests({ votingAccount }) {
                 secondary={prettyFormatNumber(voteStatsDialogData.correctlyRevealedVotesPct) + "% of Revealed Votes"}
               />
             </ListItem>
+            <ListItem>
+              <ListItemText
+                primary={"Rewards Available: " + prettyFormatNumber(voteStatsDialogData.roundInflationRewardsAvailable)}
+                // I don't use `prettyFormatNumber` here because for some reason it rounds 0.0005 to 0.001
```
Comment (nicholaspai) [inline voter-dapp/src/ResolvedRequests.js:144]: @chrismaree @mrice32 i can't figure out why `.toLocaleString({ minimumFractionDigits: 4 })` cuts `0.0005` to `0.001`

Comment (mrice32) [reply voter-dapp/src/ResolvedRequests.js:144]: I tried out a few examples here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString. For whatever reason, I don't think this actually does what we think it does. I've looked at the docs, and I can't figure out where the issue is, but for now it's probably better to just avoid it and print the raw number or use toFixed. Note: I might also suggest avoiding it in other places (like the line above) as well since it's not behaving as you expect.

Comment (nicholaspai) [reply voter-dapp/src/ResolvedRequests.js:144]: @mrice32 the main advantage of `.toLocaleString()` to me is that it puts in comma's every 3 digits :)
