### PR TITLE
fix(affiliates): winston logger configured to log only to stderr

### LINKED ISSUE #2683: winston logging to console breaks affiliate script composibility
**Description**

When errors happen during dev mining run within a price feed, winston is currently configured to log to console. This ends up breaking the output when piping it into the next app for consumption.

**Reproduction**
This is currnetly happening when trying to run the tradermade feed for ustonks.

**Expected Behavior**

Errors should log to std.err and any level below that can be ignored.

### PR DESCRIPTION
**Pull request by daywiss**
**Motivation**

#2683 

**Summary**

Just adjust winston logger to send errors to std.err

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [x]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [ ]  All existing tests pass
- [ ]  Untested

**Issue(s)**

Fixes #2683

### CODE REVIEW

File: packages/affiliates/libs/synthPrices.js [hunk 1]
```diff
@@ -9,7 +9,14 @@ module.exports = ({ web3, cryptowatchApiKey, tradermadeApiKey, decimals = 18 } =
     from = from / 1000;
     to = to / 1000;
     const priceFeed = await createReferencePriceFeedForFinancialContract(
-      winston.createLogger({ transports: [new winston.transports.Console()] }),
+      winston.createLogger({
+        transports: [
+          new winston.transports.Console({
+            level: "error",
+            stderrLevels: ["emerg", "alert", "crit", "error"]
```
Comment (chrismaree) [inline packages/affiliates/libs/synthPrices.js:16]: I dont think you need to define the log levels above the log you are curious in. you should be able to just define `error` and it will log everything above that.

**Review by chrismaree — APPROVED** [review]

File: packages/affiliates/libs/synthPrices.js [hunk 2]
```diff
@@ -9,7 +9,14 @@ module.exports = ({ web3, cryptowatchApiKey, tradermadeApiKey, decimals = 18 } =
     from = from / 1000;
     to = to / 1000;
     const priceFeed = await createReferencePriceFeedForFinancialContract(
-      winston.createLogger({ transports: [new winston.transports.Console()] }),
+      winston.createLogger({
+        transports: [
+          new winston.transports.Console({
+            level: "error",
```
Comment (nicholaspai) [inline packages/affiliates/libs/synthPrices.js:15]: Why do you define `level: "error"`? I don't think this affects what gets sent to `stdErr`, which is defined in the `stderrLevels` key below. 

I think what you're doing here by setting `level: error` is only logging error or higher logs, which might be what you're intending but FYI

Comment (mrice32) [reply packages/affiliates/libs/synthPrices.js:15]: Agreed. @daywiss why not just apply this to _all_ log levels?

**Review by mrice32 — APPROVED** [review]
LGTM outside of @nicholaspai's comment.

File: packages/affiliates/libs/synthPrices.js (hunk 2 above)
Comment (daywiss) [reply packages/affiliates/libs/synthPrices.js:15]: maybe my understanding is wrong, but i thought this would log all messages at level `error` or more critical, and suppress any info/debug logs.

Then in stderLevels i want any logs error and above to log to `error` and not `out`

Comment (nicholaspai) [reply packages/affiliates/libs/synthPrices.js:15]: Ah then I think you're right. You're specifying you want want logs at error or higher
