### PR TITLE
Workaround for non reverting view methods bug

### LINKED ISSUE #717: Strange liquidation price for expired contracts
Screenshot:
Screen Shot 2019-10-17 at 6 31 46 AM

### PR DESCRIPTION
**Pull request by mrice32**
The strange liquidation price was due to a bug in how public networks + web3 deal with reverting view methods. See https://forum.openzeppelin.com/t/require-in-view-pure-functions-dont-revert-on-public-networks/1211 for more on this issue. This PR adds a workaround to allow the dApp to continue to work correctly.

Fixes #717

### CODE REVIEW

File: sponsor-dapp-v2/src/lib/custom-hooks.js [hunk 1]
```diff
@@ -6,6 +6,33 @@ import { MAX_UINT_VAL } from "common/Constants";
...
+  };
+
+  if (isObject(result)) {
+    // Iterate over the properties of the object and see if any match the revert value.
+    for (let prop in result) {
+      if (result[prop].toString() === revertValue) {
+        return null;
+      }
+    }
+  }
```
Comment (ptare) [inline sponsor-dapp-v2/src/lib/custom-hooks.js]: Can you explain why you don't need to return `result` from here if there wasn't a revert?

Comment (mrice32) [reply sponsor-dapp-v2/src/lib/custom-hooks.js]: Nope, I just forgot to add that line. Nice catch.
