### PR TITLE
Fix some MetaMask bugs

### LINKED ISSUE #953: CLI utility shows wrong etherscan links when generating tx
Right now the CLI utility always generates a link to etherscan.io, even if running on test net or local.
image
This should dynamically change based on the network.

### PR DESCRIPTION
**Pull request by nicholaspai**
- Signing messages is different on MetaMask than Truffle, so need to call `deriveKeyPairFromSignatureMetamask` (from `Crypto.js`) when commiting and revealing votes, now commit, reveal work well
- Reading past event logs (via `web3.contract.getPastEvents`) doesn't work all the time, notably it works sometimes for reading `VoteRevealed` events but has never worked for `PriceResolved`. These events are needed to retrieve rewards and show price resolution results, respectively. Therefore, I have added checks to detect if the user is using a metamask provider and to subsequently block certain functionality if so.
- I have added messaging to communicate to the user that metamask may not work for certain functionality
- I forked `node-metamask` and fixed a bug where it does not properly convert scientific notation into numbers, notably when calling `web3.eth.getBalance()` on an account with a lot of ETH (e.g. 10,000 ETH), it retrieves this result as "1e+22" instead of "10000....000" which causes downstream bignumber errors. I made a [PR](https://github.com/JoinColony/node-metamask/pull/16) into the main `node-metamask` repo about this.

This is part of #901 

Resolves #953

### CODE REVIEW

**Comment by mrice32** [comment]
@chrismaree could you take a first pass on this?

File: common/VotingUtils.js [hunk 1]
```diff
@@ -17,8 +22,15 @@ const constructCommitment = async (request, roundId, web3, price, account) => {
   const hash = web3.utils.soliditySha3(priceWei, salt);
 
   const vote = { price: priceWei, salt };
-  const { publicKey } = await deriveKeyPairFromSignatureTruffle(web3, getKeyGenMessage(roundId), account);
-  const encryptedVote = await encryptMessage(publicKey, JSON.stringify(vote));
+  let derivedPublicKey;
+  if (web3.currentProvider.label === "metamask") {
```
Comment (mrice32) [inline common/VotingUtils.js]: nit: this is kinda nonstandard. Why not grab the `--network` arg like we do here: https://github.com/UMAprotocol/protocol/blob/904e0454b1bc09903add91fe0b562f32c7de0faf/common/MetaMaskTruffleProvider.js#L48.

You'll have to initialize minimist like we do here: https://github.com/UMAprotocol/protocol/blob/904e0454b1bc09903add91fe0b562f32c7de0faf/common/MetaMaskTruffleProvider.js#L2

File: core/scripts/cli/voting/displayStatus.js [hunk 2]
```diff
@@ -26,13 +26,16 @@ const displayVoteStatus = async (web3, voting, designatedVoting) => {
...
   const currentTime = await voting.getCurrentTime();
   // If the user is using the two key contract, then the account is the designated voting contract's address
   const account = designatedVoting ? designatedVoting.address : await getDefaultAccount(web3);
   const filteredRequests = await filterRequests(pendingRequests, account, roundId, roundPhase, voting);
   const rewards = await getAvailableRewards(web3, voting, account);
-  const resolvedPrices = await getResolvedPrices(web3, voting, account);
+  // TODO(#901): MetaMask provider sometimes has trouble reading past events
+  let resolvedPrices;
+  if (web3.currentProvider.label !== "metamask") {
+    resolvedPrices = await getResolvedPrices(web3, voting, account);
```
Comment (mrice32) [inline core/scripts/cli/voting/displayStatus.js]: WDYT about handling this in getResolvedPrices instead of wrapping it in an if, just so the solution is closer to the problem?

File: common/VotingUtils.js (hunk 1 above)
Comment (nicholaspai) [reply common/VotingUtils.js]: Much better this way thanks!

File: core/scripts/cli/voting/displayStatus.js (hunk 2 above)
Comment (nicholaspai) [reply core/scripts/cli/voting/displayStatus.js]: good idea

File: common/VotingUtils.js (hunk 1 above)
Comment (nicholaspai) [reply common/VotingUtils.js]: done

File: core/scripts/cli/voting/displayStatus.js (hunk 2 above)
Comment (nicholaspai) [reply core/scripts/cli/voting/displayStatus.js]: done

File: common/VotingUtils.js [hunk 3]
```diff
@@ -17,8 +24,15 @@ const constructCommitment = async (request, roundId, web3, price, account) => {
   const hash = web3.utils.soliditySha3(priceWei, salt);
 
   const vote = { price: priceWei, salt };
-  const { publicKey } = await deriveKeyPairFromSignatureTruffle(web3, getKeyGenMessage(roundId), account);
-  const encryptedVote = await encryptMessage(publicKey, JSON.stringify(vote));
+  let derivedPublicKey;
+  if (argv.network === "metamask") {
+    const { publicKey } = await deriveKeyPairFromSignatureMetamask(web3, getKeyGenMessage(roundId), account);
```
Comment (mrice32) [inline common/VotingUtils.js]: If you change `derivedPublicKey` back to `publicKey`, you can do this assignment like this:
```
({ publicKey } = await deriveKeyPairFromSignatureMetamask(web3, getKeyGenMessage(roundId), account));
```
or like this:
```
publicKey = (await deriveKeyPairFromSignatureMetamask(web3, getKeyGenMessage(roundId), account)).publicKey;
```

File: common/VotingUtils.js [hunk 4]
```diff
@@ -42,8 +56,15 @@ const constructReveal = async (request, roundId, web3, account, votingContract)
   const topicHash = computeTopicHash(request, roundId);
   const encryptedCommit = await votingContract.getMessage(account, topicHash, { from: account });
 
-  const { privateKey } = await deriveKeyPairFromSignatureTruffle(web3, getKeyGenMessage(roundId), account);
-  const vote = JSON.parse(await decryptMessage(privateKey, encryptedCommit));
+  let derivedPrivateKey;
+  if (argv.network === "metamask") {
+    const { privateKey } = await deriveKeyPairFromSignatureMetamask(web3, getKeyGenMessage(roundId), account);
```
Comment (mrice32) [inline common/VotingUtils.js]: Same comment as above.

File: common/VotingUtils.js (hunk 3 above)
Comment (nicholaspai) [reply common/VotingUtils.js]: nice saves a variable

Comment (nicholaspai) [reply common/VotingUtils.js]: done

File: common/VotingUtils.js (hunk 4 above)
Comment (nicholaspai) [reply common/VotingUtils.js]: done
