### PR TITLE
bug(liquidatable): snapshot funding-rate adjusted token debt at liquidation, not settlement, time

### LINKED ISSUE #2211: Perp Liquidatable: snapshot funding-rate-adjusted tokens liquidated at liquidation time
**Description**

`tokensLiquidated` are saved in a liquidation struct and then reevaluated against `lockedCollateral` in `withdrawLiquidationRewards` to determine whether a liquidation is valid. However, the `fundingRateMultiplier` can change in between liquidation and dispute-settlement time and therefore the value of `getFundingRateAdjustedTokenDebt(tokensLiquidated)` can change in between liquidation and dispute-settlement time.

This is not an issue with the `feeMultiplier` because the `lockedCollateral` that is saved at liquidation time is derived from `_getFeeAdjustedCollateral(positionToLiquidate.rawCollateral)`. So, we should simply adjust the `tokensLiquidated` taking into account the `fundingRateMultiplier` **at liquidation time, not dispute-settlement time**.

**Reproduction**

The following test case should pass:
- Funding rate is set to non-0
- Funding rate multiplier initially set to 1
- CR = 150%
- Liquidate 10 tokens backed by 15 collateral, assume oracle price = 1.
- Dispute liquidation
- Advance time forward such that funding rate multiplier increases (e.g. `getFundingRateAdjusted(X) != X`)
- Without funding rate multiplier increasing, the liquidation is INVALID because 15 collateral backing 10 tokens = 150% collateralized
- With funding rate multiplier increasing, the new CR is 15/ (>10) < 150% collateralized, so liquidation would now  be VALID if the liquidation's `getFundingRateAdjustedTokenDebt(tokensLiquidated)`  is snapshotted at dispute-settlement time. Instead, if the contract snapshots `getFundingRateAdjustedTokenDebt(tokensLiquidated)`  at liquidation time then the liquidation should be INVALID

The test should resolve that the liquidation was INVALID

**Expected Behavior**

Unit tests pass

### PR DESCRIPTION
**Pull request by nicholaspai**
**Motivation**

#2211

**Summary**

**Details**

**Issue(s)**

Fixes #2211

### CODE REVIEW

**Review by mrice32 — COMMENTED** [review]
Did you mean to include all of these formatting changes?

File: packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js [hunk 1]
```diff
@@ -1457,6 +1426,175 @@ contract("PerpetualLiquidatable", function(accounts) {
...
+      // Check that liquidation struct and event stores the correct funding-rate adjusted # of tokens.
+      assert.equal((await liquidationContract.liquidations(sponsor, 0)).tokensOutstanding.toString(), toWei("105"));
+      truffleAssert.eventEmitted(liquidationResult, "LiquidationCreated", ev => {
+        return ev.tokensOutstanding.toString() === toWei("105");
+      });
+
+      // Reset final fee to 0 post liquidation.
+      await store.setFinalFee(collateralToken.address, { rawValue: "0" });
+
+      // Mint final fee amount to disputer
```
Comment (chrismaree) [inline packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js:1573]:
```suggestion
      // Mint final fee amount to disputer.
```

File: packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js [hunk 2]
```diff
@@ -1457,6 +1426,175 @@ contract("PerpetualLiquidatable", function(accounts) {
...
+        return ev.tokensOutstanding.toString() === toWei("95");
+      });
+
+      // Reset final fee to 0 post liquidation.
+      await store.setFinalFee(collateralToken.address, { rawValue: "0" });
+
+      // Mint final fee amount to disputer
+      await collateralToken.mint(disputer, finalFeeAmount, { from: contractDeployer });
+
+      // Dispute the created liquidation
```
Comment (chrismaree) [inline packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js:1504]:
```suggestion
      // Dispute the created liquidation.
```

File: packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js [hunk 3]
```diff
@@ -1457,6 +1426,175 @@ contract("PerpetualLiquidatable", function(accounts) {
...
+      // Check that liquidation struct and event stores the correct funding-rate adjusted # of tokens.
+      assert.equal((await liquidationContract.liquidations(sponsor, 0)).tokensOutstanding.toString(), toWei("95"));
+      truffleAssert.eventEmitted(liquidationResult, "LiquidationCreated", ev => {
+        return ev.tokensOutstanding.toString() === toWei("95");
+      });
+
+      // Reset final fee to 0 post liquidation.
+      await store.setFinalFee(collateralToken.address, { rawValue: "0" });
+
+      // Mint final fee amount to disputer
```
Comment (chrismaree) [inline packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js:1501]:
```suggestion
      // Mint final fee amount to disputer.
```

File: packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js [hunk 4]
```diff
@@ -1457,6 +1426,175 @@ contract("PerpetualLiquidatable", function(accounts) {
...
+      await liquidationContract.create(
+        { rawValue: amountOfCollateral.toString() },
+        { rawValue: amountOfSynthetic.toString() },
+        { from: sponsor }
+      );
+
+      // Set final fee before initiating the liquidation.
+      await store.setFinalFee(collateralToken.address, { rawValue: finalFeeAmount.toString() });
+
+      // Transfer synthetic tokens to a liquidator
```
Comment (chrismaree) [inline packages/core/test/financial-templates/perpetual-multiparty/PerpetualLiquidatable.js:1446]:
```suggestion
      // Transfer synthetic tokens to a liquidator.
```

**Review by chrismaree — APPROVED** [review]
This looks great! nice and clean. Good commenting and tests.

File: packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol [hunk 5]
```diff
@@ -252,11 +252,13 @@ contract PerpetualLiquidatable is PerpetualPositionManager {
             startCollateralNetOfWithdrawal = startCollateral.sub(positionToLiquidate.withdrawalRequestAmount);
         }
 
-        // Scoping to get rid of a stack too deep error.
+        // Scoping to get rid of a stack too deep error. In this block, we use the funding-rate adjusted value
+        // of token debt to check that the desired liquidation price is valid.
         {
-            FixedPoint.Unsigned memory startTokens = positionToLiquidate.tokensOutstanding;
+            FixedPoint.Unsigned memory startTokens =
```
Comment (mrice32) [inline packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol:258]: nit: shouldn't this be un-adjusted since it's compared to the user-provided values of collateral per token? And the user's idea of a token is non-adjusted?

Comment (nicholaspai) [reply packages/core/contracts/financial-templates/perpetual-multiparty/PerpetualLiquidatable.sol:258]: But `positionToLiquidate` is equal to `_getPositionData(sponsor)` so isnt it reading the sponsor's on-chain state?
