### PR TITLE
fix(affiliates): switch between price feed output and also convert time to ms

### LINKED ISSUE #2462: Developer mining script is unable to get price history from non medianizer feeds
**Description**

see #2461 which outlines why devmining script breaks on non medianized price feeds. This will require a quick fix in order to run rewards for the week since dom finance has been added and it does not by default load a medianized feed. 

Additionally it turns out medianized prices are timestamped in seconds, so these need to be converted to MS for dev mining to be able to look up prices properly.

**Reproduction**

Run dev mining with a dom finance address such as `0xeFA41F506EAA5c24666d4eE40888bA18FA60a1c7` and see that the app crashes with strange error.

**Expected Behavior**

Dev mining needs to detect output from price feed classes and determine how to properly parse them for now, until these outputs can be standardized. Dev mining also needs to convert timestamps from seconds to ms.

### PR DESCRIPTION
**Pull request by daywiss**
**Motivation**

#2462 

**Summary**
This is  a quick fix that needed to be added in order to run dev mining for this week due to the inclusion of dom finance.

- When querying synthetic price the dev mining processor will switch between different output types by detecting if its an 
array or not
- convert synthetic time from S to MS.
- do not check valid addresses for payout addresses so that we can support running script before partner address is given

**Testing**

Check a box to describe how you tested these changes and list the steps for reviewers to test.

- [x]  Ran end-to-end test, running the code as in production
- [ ]  New unit tests created
- [ ]  Existing tests adequate, no new tests required
- [x]  All existing tests pass
- [ ]  Untested

**Issue(s)**

Fixes #2462

### CODE REVIEW

**Review by chrismaree — APPROVED** [review]
Looks good! nice to be able to not know the payout address. id argue we want this to be uniform but I understand there is a business need for this functionality.

File: packages/affiliates/libs/affiliates/devmining.js [hunk 1]
```diff
@@ -87,10 +87,25 @@ module.exports = ({ queries, empAbi, coingecko, synthPrices, firstEmpDate }) =>
...
   async function getSyntheticPriceHistory(address, start, end) {
     const result = await synthPrices.getHistoricSynthPrices(address, start, end);
-    return Prices(result);
+    // Turns out getHistoricPriceFeed differs between price feed classes. This needs to be fixed
+    // but for now we will detect it and switch between decodings.
+    const fixedPrices = result.map(price => {
+      if (isMedianizerPrice(price)) return decodeMedianizerPrice(price);
+      return decodeOtherPrice(price);
+    });
+    return Prices(fixedPrices);
```
Comment (mrice32) [inline packages/affiliates/libs/affiliates/devmining.js:108]: Yeah, we should definitely fix the underlying price feed. Can you add a TODO?

**Review by mrice32 — APPROVED** [review]

File: packages/affiliates/libs/affiliates/devmining.js (hunk 1 above)
Comment (daywiss) [reply packages/affiliates/libs/affiliates/devmining.js:109]: for reference see #2461. ive also added a todo
