### PR TITLE
fix(voter-dapp): direct user to download metamask if web3 is not detected

### LINKED ISSUE #1962: not having metamask plugin causes voter dapp to error
**Description**

Started voter dapp development `yarn start` and opened localhost:3000.  Gave me error in screen

**Reproduction**
Open page without metamask installed. Will white screen in production and show error below in dev.

**Expected Behavior**

Should probably tell you to install metamask. 

**Screenshots**

image

### PR DESCRIPTION
**Pull request by daywiss**
**Motivation**

#1962 

**Summary**
Added some logic to detect if web3 exists by checking the window.ethereum object. If nothing found it will default to a button which tells user to get metamask. If metamask is found, it will show the standard login button. 

**Details**
This is what the user sees if metamask is not installed after this change. 
image

**Issue(s)**

Fixes #1962

### CODE REVIEW

File: packages/voter-dapp/src/DrizzleLogin.js [hunk 1]
```diff
@@ -8,6 +8,11 @@ import DrizzleInit from "./DrizzleInit.js";
 function DrizzleLogin(props) {
   const [isButtonDisabled, setButtonDisabled] = useState(false);
   const [drizzle, setDrizzle] = useState(null);
+  const [hasMetamask, setHasMetamask] = useState(false);
+
+  const getMetamask = () => {
+    window.open("https://metamask.io/", "_blank");
```
Comment (nicholaspai) [inline packages/voter-dapp/src/DrizzleLogin.js:14]: I've never used `window.open()` to open a link, only `<a>` tag's with `url` and `target` props set. Cool stuff

**Review by nicholaspai — APPROVED** [review]
Simple feature that can go a long way, LGTM!

**Review by chrismaree — APPROVED** [review]
