### PR TITLE
fix(bots) Fix liquidator and disputer expiry logic

### LINKED ISSUE #2067: Liquidator/Disputer bot: Cannot withdraw rewards after an EMP expires
**Description**

We had a user run a disputer bot who disputed shortly before expiry. By the time the dispute had resolved, the EMP had already expired, and the bot returned early (as designed).

**Expected Behavior**

Disputer and Liquidator bot should be able to withdraw rewards after expiry

### LINKED ISSUE #2068: Disputer and Liquidator bots compare expirationTimestamp to contractTimestamp incorrectly
**Description**

[Liquidator](https://github.com/UMAprotocol/protocol/blob/master/packages/liquidator/index.js#L83) and [Disputer](https://github.com/UMAprotocol/protocol/blob/master/packages/disputer/index.js#L68) bots do not cast timestamps to numbers when checking if a contract has expired. 

This has worked in practice with realistic timestamps, for example:

```sh
> node
Welcome to Node.js v12.14.1.
> "1601996024" >= "1601996023"
true
```

But gives a false positive in the tests [here (disputer)](https://github.com/UMAprotocol/protocol/blob/master/packages/disputer/test/index.js#L145) and [here (liquidator)](https://github.com/UMAprotocol/protocol/blob/master/packages/liquidator/test/index.js#L148).

```sh
> node
Welcome to Node.js v12.14.1.
> "11345678900" >= "20345678900"
false
```

**Resolution**

Bots should cast timestamps to numbers before comparing, and tests need to be rewritten

### PR DESCRIPTION
**Pull request by nicholaspai**
Signed-off-by: Nick Pai <npai.nyc@gmail.com>

**Motivation**

#2067 
#2068 

**Summary**

Removed all expiration logic in disputer as you can dispute and withdraw rewards post-expiry + tests

Liquidator should attempt to withdraw rewards post-expiry + tests

**Issue(s)**

Fixes #2067 
Fixes #2068

### CODE REVIEW

File: packages/liquidator/test/index.js [hunk 1]
```diff
@@ -163,8 +159,127 @@ contract("index.js", function(accounts) {
...
     }
 
-    // There should only be 1 log that communicates that bot is exiting early
+    // There should only be 1 log that communicates that bot is exiting early,
+    // which indicates that no approvals were sent.
+    assert.equal(spy.getCalls().length, 1);
+    assert.isTrue(spyLogIncludes(spy, 0, "expired"));
+  });
+
+  it("Post EMP expiry, liquidator can withdraw rewards but will not attempt to liquidate any undercollateralized positions", async function() {
```
Comment (nicholaspai) [inline packages/liquidator/test/index.js:168]: This is the new test: a liquidation is disputed and resolved post-expiry, test that the liquidator can withdraw rewards from it

File: packages/liquidator/index.js [hunk 2]
```diff
@@ -79,15 +79,16 @@ async function run({
...
+    if (Number(contractTimestamp) >= Number(expirationTimestamp)) {
       logger.info({
         at: "Liquidator#index",
-        message: "EMP is expired, cannot liquidate any positions 🕰",
+        message: "EMP is expired, can only withdraw dispute rewards 🕰",
         expirationTimestamp,
         contractTimestamp
       });
-      return;
+      isExpired = true;
```
Comment (mrice32) [inline packages/liquidator/index.js:91]: nit: thoughts on either moving `isExpired` into the loop or resetting the value in the loop? I only say this because the contract can become expired while the loop is running, right?

**Review by mrice32 — COMMENTED** [review]
This is awesome! The new tests look great! One small comment about where we're setting `isExpired`.

File: packages/liquidator/index.js (hunk 2 above)
Comment (nicholaspai) [reply packages/liquidator/index.js:91]: we should reset it in the loop, but I wanted to initialize it outside the loop so that we don't unneccessarily approve any allowances

File: packages/liquidator/index.js [hunk 3]
```diff
@@ -190,14 +192,31 @@ async function run({
 
     // Create a execution loop that will run indefinitely (or yield early if in serverless mode)
     for (;;) {
+      // Check if EMP is expired.
+      const [expirationTimestamp, contractTimestamp] = await Promise.all([
```
Comment (nicholaspai) [inline packages/liquidator/index.js:196]: @mrice32 here I will set isExpired if it expires during the loop

File: packages/liquidator/index.js (hunk 2 above)
Comment (mrice32) [reply packages/liquidator/index.js:91]: yup, SGTM!

File: packages/liquidator/index.js (hunk 3 above)
Comment (mrice32) [reply packages/liquidator/index.js:196]: nit: does this shadow the external variables? Could you do this?
```
      [expirationTimestamp, contractTimestamp] = await Promise.all([
        emp.methods.expirationTimestamp().call(),
        emp.methods.getCurrentTime().call()
      ]);

File: packages/liquidator/index.js (hunk 2 above)
Comment (nicholaspai) [reply packages/liquidator/index.js:91]: I might try to functionalize this logic or make isEnded a more obvious setting by calling is IS_ENDED wdyt?

File: packages/liquidator/index.js [hunk 4]
```diff
@@ -60,35 +60,45 @@ async function run({
     const voting = new web3.eth.Contract(getAbi("Voting"), getAddress("Voting", networkId));
     const emp = new web3.eth.Contract(getAbi("ExpiringMultiParty"), empAddress);
 
+    // Returns whether the EMP has expired yet
+    const checkIsExpiredPromise = async () => {
```
Comment (nicholaspai) [inline packages/liquidator/index.js:64]: @mrice32 I went ahead and wrapped this in a promise which we can add to the parallel promise below. Thought this was cleaner

File: packages/liquidator/index.js (hunk 3 above)
Comment (nicholaspai) [reply packages/liquidator/index.js]: Yeah you're right, but I ended up stripping out this logic into its own arrow function

File: packages/liquidator/index.js (hunk 4 above)
Comment (mrice32) [reply packages/liquidator/index.js:64]: nit: why not just `checkIsExpired`? IMO, calling it `promise` makes it sound like it's a promise rather than a function.

**Review by mrice32 — APPROVED** [review]
LGTM!

**Review by chrismaree — APPROVED** [review]

**Review by daywiss — APPROVED** [review]

File: packages/disputer/index.js [hunk 5]
```diff
@@ -57,24 +57,11 @@ async function run({
...
+    const [priceIdentifier, collateralTokenAddress] = await Promise.all([
       emp.methods.priceIdentifier().call(),
-      emp.methods.collateralCurrency().call(),
-      emp.methods.expirationTimestamp().call(),
-      emp.methods.getCurrentTime().call()
+      emp.methods.collateralCurrency().call()
     ]);
 
-    // If EMP is expired, exit early.
-    if (contractTimestamp >= expirationTimestamp) {
```
[the remark this answers is not in the document]
Comment (nicholaspai) [reply packages/disputer/index.js:68]: Nope yeah, the disputer will only dispute unexpired liquidations,

but you CAN dispute post-expiry (and withdraw rewards) so no need to worry about contract expiry

[the remark this answers is not in the document]
Comment (chrismaree) [reply packages/disputer/index.js:68]: sgtm!
