### PR TITLE
Preserve error stack trace details in Winston logs

### LINKED ISSUE #1406: Monitor bot `index.js` test
Our bot infrastructure has tests for `index.js` in all contexts except the monitor bot. This should be updated.

### LINKED ISSUE #1616: Improve bot stack traces
Right now the stack traces are not super useful and this should be refined.

### PR DESCRIPTION
**Pull request by nicholaspai**
Resolves #1616 

Currently, we are losing error stack trace details. Notice how the trace points only to the bot's root `catch` statement in `monitors/index.js` for example:
Screen Shot 2020-06-17 at 11 50 19

This is because we are recasting the caught `error` as a `new Error(error)`. Every time an new Error is created, its stack is reset. We did this previously because some `error`'s that bubbled up to the root `catch` statement were of the String type `(typeof error === "string)`. These String errors are created when we throw errors like so: `throw "I am a string error"`.

___
So, this fix first adds a ternary check to any module that creates a Winston log with an `error` property. Previously we were sending errors like so:
```
Logger.error({
      at: "Monitor#index",
      message: "Monitor polling error. Monitor crashed🚨",
      error: new Error(error)
});
```

However, oftentimes this `error` was already an `Error` type with a stack trace, so we shouldn't automatically delete the old stack trace. We should change all similar `Logger.error()` to:
```
Logger.error({
      at: "Monitor#index",
      message: "Monitor polling error. Monitor crashed🚨",
      error: typeof error === "string" ? new Error(error) : error
 });
```

This is the new Slack output:
Screen Shot 2020-06-17 at 12 03 57

___

`ConsoleTransport.js` also needs to be changed so that it no longer checks for the `error.stack` property of the `info.error` input. This is because one of the methods called before `ConsoleTransport.js: combine()` is `Logger.js: errorStackTracerFormatter()` which strips out the error's `stack` property and inserts it into the `info`'s error property.

___
 
Other fixes:
- Adds a unit test to `monitors/index.js`: resolves #1406 
- There is a bad typo "err" in `monitors/index.js`. This caused all errors in the `Poll()` method to be ignored.

Signed-off-by: Nick Pai <npai.nyc@gmail.com>

### CODE REVIEW

File: disputer/disputer.js [hunk 1]
```diff
@@ -114,7 +114,7 @@ class Disputer {
           message: "Cannot dispute liquidation: not enough collateral (or large enough approval) to initiate dispute✋",
           sponsor: disputeableLiquidation.sponsor,
           liquidation: disputeableLiquidation,
-          error: new Error(error)
+          error: typeof error === "string" ? new Error(error) : error
```
Comment (nicholaspai) [inline disputer/disputer.js:117]: Looking at this code made me realize that we send Logger.errors from both `disputer/disputer.js` and `disputer/index.js` (same with `liquidator/index.js` and `liquidator/liquidator.js`)

This style is inconsistent with how we log errors in `monitors`, which only sends errors from the root `index.js`, but none of the `ContractMonitor/BalanceMonitor/CRMonitor/etc.` send Logger errors. Instead, they either send `Logger.warn`'s or they just throw errors that get caught by the `index.js`.

What are your opinions on how to handle this? I suggest we replace these `Logger.error's` with `Logger.warn`'s.

File: disputer/index.js [hunk 2]
```diff
@@ -91,13 +91,17 @@ async function run(address, shouldPoll, pollingDelay, priceFeedConfig, disputerC
 const Poll = async function(callback) {
   try {
     if (!process.env.EMP_ADDRESS) {
-      throw "Bad input arg! Specify an `EMP_ADDRESS` for the location of the expiring Multi Party within your environment variables.";
```
Comment (nicholaspai) [inline disputer/index.js:94]: By changing this from type `string => object`, the Winston error log will print a stack trace to line 94 of `disputer/index.js` instead of just printing a stack trace to line 121 at the root `catch`

File: financial-templates-lib/logger/ConsoleTransport.js [hunk 3]
```diff
@@ -18,10 +18,9 @@ const customFormat = combine(
     // Winston does not properly log Error objects like console.error() does, so this formatter will search for the Error object
     // in the "error" property of "info", and add the error stack to the log.
     // Discussion at https://github.com/winstonjs/winston/issues/1338.
-    if (error && error.stack) {
```
Comment (nicholaspai) [inline financial-templates-lib/logger/ConsoleTransport.js:21]: Removing this check for `error.stack` means that `ConsoleTransport` is necessary because by the time `error`'s are sent to this module they already have had their `stack` stripped out by `Logger.js: errorStackTracerFormatter()`

File: monitors/index.js [hunk 4]
```diff
@@ -256,11 +262,11 @@ const Poll = async function(callback) {
       uniswapPriceFeedConfig,
       medianizerPriceFeedConfig
     );
-  } catch (err) {
```
Comment (nicholaspai) [inline monitors/index.js:259]: This was an evil typo

File: disputer/disputer.js (hunk 1 above)
Comment (mrice32) [reply disputer/disputer.js:117]: This is a good question.

The way I see it, there are three classes of errors:
1. Errors where the process cannot move forward. Most of these are thrown by libraries out of our control or occur during initialization. Examples would include a node query that fails (and we can't force a retry) or an invalid config.
2. Errors where the process can move forward with other work despite the error. Examples are when the liquidator or disputer wants to send a transaction, but it fails for some reason.
3. Errors that don't cause the process to crash and aren't necessarily an actionable issue, but may signal a problem or just be useful for us to know about.

IMO:
1. Should be handled by a high-level catch that emits the logger error. 
2. Should be emitted by the inner process without triggering a crash, so other work isn't interrupted.
3. Should be a warning emitted by the inner process.

Comment (mrice32) [reply disputer/disputer.js:117]: My intuition says that the liquidator and disputer have instances of 2, whereas the monitors really don't, which is why they don't throw any `logger.error`s outside of the catch.

Comment (nicholaspai) [reply disputer/disputer.js:117]: I agree with classifying these liquidator/disputer catches under #2. However, if we ever want to add additional logic to the error handling beyond just the ternary checking whether the `error` is a string or an object, then this will create additional work.

Since these are smart contract revert errors, perhaps we should just assume that they are of type Error and just set `error: error`?

Comment (nicholaspai) [reply disputer/disputer.js]: Follow up: I made this change. No need to check if an error returned by a web3.send/web3.call is a string, we can assume it is an `Error`.

File: monitors/index.js (hunk 4 above)
Comment (chrismaree) [reply monitors/index.js:259]: jeez! great catch with this. no wonder we were getting such inconsistent reporting in so many cases form this bot.

File: disputer/disputer.js [hunk 5]
```diff
@@ -144,7 +144,7 @@ class Disputer {
         this.logger.error({
           at: "Disputer",
           message: "Failed to dispute liquidation🚨",
-          error: new Error(error)
+          error
```
Comment (chrismaree) [inline disputer/disputer.js:147]: +1 much cleaner.

File: monitors/test/index.js [hunk 6]
```diff
@@ -0,0 +1,121 @@
...
+      volatilityWindow: 600,
+      volatilityAlertThreshold: 0.1
+    };
+
+    // Set two uniswap prices to give it a little history.
+    await uniswap.setPrice(toWei("1"), toWei("1"));
+    await uniswap.setPrice(toWei("1"), toWei("1"));
+  });
+
+  it("Completes one iteration without throwing an error", async function() {
```
Comment (chrismaree) [inline monitors/test/index.js:100]: Perfect! thanks for adding this test. Also good that we kept it to 1 test as PR #1608 introduces some nasty restrictions around the `index.js` tests.
