### PR TITLE
NewSponsor events monitor + fixing bot error-catching bugs that I ran into

### LINKED ISSUE #1506: Add logic to track new sponsor positions in monitor bot

### PR DESCRIPTION
**Pull request by nicholaspai**
Adds `NewSponsor` event tracker to `ExpiringMultiPartyEventClient`.

Fixes bug in this client that sets `this.lastBlockNumberSeen = currentBlock` to `this.lastBlockNumberSeen = currentBlock + 1` so that events in the last block are not double-counted.

Fix bugs in `CRMonitor` and `SyntheticPegMonitor` that attempt to print values from an `undefined` object in cases where the monitors fail to fetch pricefeed data.

Example slack message for `NewSponsor` monitor:
Screen Shot 2020-05-26 at 11 19 47

Resolves #1506

### CODE REVIEW

File: monitors/CRMonitor.js [hunk 1]
```diff
@@ -42,8 +42,7 @@ class CRMonitor {
     if (!price) {
       this.logger.warn({
         at: "CRMonitor",
-        message: "Cannot compute wallet collateralization ratio because price feed returned invalid value",
-        price: price.toString()
+        message: "Cannot compute wallet collateralization ratio because price feed returned invalid value"
```
Comment (nicholaspai) [inline monitors/CRMonitor.js:45]: This throws an error because `price == undefined`

File: financial-templates-lib/clients/ExpiringMultiPartyEventClient.js [hunk 2]
```diff
@@ -94,7 +99,31 @@ class ExpiringMultiPartyEventClient {
...
+        transactionHash: event.transactionHash,
+        blockNumber: event.blockNumber,
+        sponsor: event.returnValues.sponsor,
+        collateralAmount: positionCreatedEventObj[0].returnValues.collateralAmount,
+        tokenAmount: positionCreatedEventObj[0].returnValues.tokenAmount
+      });
+    }
+
+    // Add 1 so that we do not double-count the actual last block number seen.
+    this.lastBlockNumberSeen = currentBlockNumber + 1;
```
Comment (mrice32) [inline financial-templates-lib/clients/ExpiringMultiPartyEventClient.js:125]: Nice find! Would it be too much trouble to change the name of this variable? The name just seems a little incorrect now.

File: monitors/ContractMonitor.js [hunk 3]
```diff
@@ -48,6 +49,52 @@ class ContractMonitor {
...
+        " backed by " +
+        this.formatDecimalString(event.collateralAmount) +
+        " " +
+        this.collateralCurrencySymbol +
+        ". tx: " +
+        createEtherscanLinkMarkdown(this.web3, event.transactionHash);
+
+      this.logger.info({
+        at: "ContractMonitor",
+        message: "New Sponsor Alert 🐣!",
```
Comment (chrismaree) [inline monitors/ContractMonitor.js:91]: This emoji!!! 😍

File: monitors/ContractMonitor.js [hunk 4]
```diff
@@ -48,6 +49,52 @@ class ContractMonitor {
...
+    let latestNewSponsorEvents = this.empEventClient.getAllNewSponsorEvents();
+
+    // Get events that are newer than the last block number we've seen
+    let newSponsorEvents = latestNewSponsorEvents.filter(event => event.blockNumber > this.lastNewSponsorBlockNumber);
+
+    for (let event of newSponsorEvents) {
+      // Check if new sponsor is UMA bot.
+      const isLiquidatorBot = this.monitoredLiquidators.indexOf(event.sponsor);
+      const isDisputerBot = this.monitoredDisputers.indexOf(event.sponsor);
+      const isUMABot = Boolean(isLiquidatorBot != -1 || isDisputerBot != -1);
```
Comment (chrismaree) [inline monitors/ContractMonitor.js:70]: the logic you've got here is good but ideally let's not use the `UMA` name in the source code. This could be `isMonitoredBot` perhaps?

File: monitors/SyntheticPegMonitor.js [hunk 5]
```diff
@@ -66,22 +66,23 @@ class SyntheticPegMonitor {
...
-      cryptoWatchTokenPrice: cryptoWatchTokenPrice.toString()
-    });
-
     if (!uniswapTokenPrice || !cryptoWatchTokenPrice) {
       this.logger.warn({
         at: "SyntheticPegMonitor",
         message: "Unable to get price",
-        uniswapTokenPrice: uniswapTokenPrice.toString(),
-        cryptoWatchTokenPrice: cryptoWatchTokenPrice.toString()
+        uniswapTokenPrice: uniswapTokenPrice ? uniswapTokenPrice.toString() : null,
```
Comment (chrismaree) [inline monitors/SyntheticPegMonitor.js:73]: +1

File: financial-templates-lib/clients/ExpiringMultiPartyEventClient.js (hunk 2 above)
Comment (nicholaspai) [reply financial-templates-lib/clients/ExpiringMultiPartyEventClient.js:125]: Easy to switch, changed to `firstBlockNumberToSearch`

File: monitors/ContractMonitor.js (hunk 4 above)
Comment (nicholaspai) [reply monitors/ContractMonitor.js:70]: good idea

Comment (mrice32) [reply monitors/ContractMonitor.js:70]: +1

File: monitors/ContractMonitor.js (hunk 3 above)
Comment (mrice32) [reply monitors/ContractMonitor.js:91]: Yeah, this is 👌👌👌👌
