### PR TITLE
Many fixes to Sponsor CLI 

### LINKED ISSUE #1499: CLI shows incorrect liquidation details, should read from events not contract
Liquidations show 0 tokens liquidated by 0x0 after a withdrawal (as expected) because liquidation state is read from contract, not from event.

### PR DESCRIPTION
**Pull request by nicholaspai**
Apologies for the big PR, but a lot of these changes depend on each other so it was easier for me to develop on the same branch. Originally I was only working on #1499 but made all of these edits along the way. Many of the changes are new helper scripts to test the sponsor CLI with liquidations, disputes, and withdrawing liquidation rewards.

New features/bug fixes:
- BigNumber config is moved to top of `create.js` so that large number strings are not automatically displayed in scientific format. This caused a bug on line 22: `const minPositionSize = BigNumber((await emp.minSponsorTokens()).toString());` which cannot cast scientific-notation string to `BigNumber`.
- Warn user before creating a position if they do not have enough collateral to create their desired new position.
- `currencyUtils.getCurrencySymbol` now attempts to call `.symbol()` on a collateral currency rather than returning a generic "collateral currency" as the collaterl token's symbol. This improves UX. 
- Add contract's current time to sponsor summary. Mostly useful for testing.
- Display token balances for convenience.
- Detect liquidation token amount data from events since this gets deleted after a liquidation is deleted post-withdrawal. 
- Add more specific error messages to `withdrawLiquidation` functionality via the CLI. 
- New helper scripts for testing sponsor CLI.
- Refactor liquidation menus into the same files, dedicated to liquidation logic.

Resolves #1499

### CODE REVIEW

File: core/scripts/cli/sponsor/viewLiquidationDetails.js [hunk 1]
```diff
@@ -1,24 +1,120 @@
...
+    // The sponsor can only withdraw rewards from a successfully disputed liquidation.
+    if (liquidation.state === LiquidationStatesEnum.PRE_DISPUTE) {
+      // If liquidation state is PRE_DISPUTE and `withdrawLiquidation` fails, then the liquidation has either expired
+      // or is pre-expiry. Only a liquidator can withdraw from an expired liquidation.
+      console.log(
+        "Cannot withdraw rewards from a liquidation that is pre-expiry and has not been disputed, or has already expired"
+      );
+    } else if (liquidation.state === LiquidationStatesEnum.PENDING_DISPUTE) {
+      // If the liquidation state is PENDING_DISPUTE and `withdrawLiquidation` fails, then it indicates that either
+      // a price has not resolved yet, or a price has resolved that indicates that the dispute will FAIL.
```
Comment (mrice32) [inline core/scripts/cli/sponsor/viewLiquidationDetails.js:95]: This is a weird (but totally valid) case. Is there any way to tell the difference between the case where the oracle has a price and the case where it doesn't?

File: core/scripts/cli/sponsor/viewLiquidationDetails.js [hunk 2]
```diff
@@ -1,24 +1,120 @@
...
     choices.push({ name: withdrawAction });
   } catch (err) {
-    // Withdraw wouldn't work so it shouldn't be a valid option.
+    // Withdraw wouldn't work so it shouldn't be a valid option. Let's print out a detailed response to the user to indicate why
+    // `withdraw` will fail.
+
+    // The sponsor can only withdraw rewards from a successfully disputed liquidation.
+    if (liquidation.state === LiquidationStatesEnum.PRE_DISPUTE) {
+      // If liquidation state is PRE_DISPUTE and `withdrawLiquidation` fails, then the liquidation has either expired
+      // or is pre-expiry. Only a liquidator can withdraw from an expired liquidation.
```
Comment (mrice32) [inline core/scripts/cli/sponsor/viewLiquidationDetails.js:89]: Can't we differentiate between these two cases by looking at the expiration time on the liqudiation?

File: core/scripts/cli/sponsor/viewLiquidationDetails.js (hunk 1 above)
Comment (nicholaspai) [reply core/scripts/cli/sponsor/viewLiquidationDetails.js:97]: Done, PTAL at the logic. I fetch Oracle from finder and check whether it has a price. If it does then that means the dispute will fail and we can change the messaging.

File: core/scripts/cli/sponsor/viewLiquidationDetails.js (hunk 2 above)
Comment (nicholaspai) [reply core/scripts/cli/sponsor/viewLiquidationDetails.js:91]: Yup easily. Done PTAL!

File: core/scripts/cli/sponsor/viewLiquidationDetails.js [hunk 3]
```diff
@@ -1,24 +1,144 @@
...
+      // a price has not resolved yet, or a price has resolved that indicates that the dispute will FAIL.
+
+      // Fetch oracle price and use it to customize error message.
+      const Finder = artifacts.require("Finder");
+      let finder = await Finder.deployed();
+      const OracleInterface = artifacts.require("OracleInterface");
+      let oracle = await OracleInterface.at(
+        await finder.getImplementationAddress(web3.utils.utf8ToHex(interfaceName.Oracle))
+      );
+      if (await oracle.hasPrice(await emp.priceIdentifier(), liquidation.liquidationTime)) {
```
Comment (mrice32) [inline core/scripts/cli/sponsor/viewLiquidationDetails.js:113]: nit: I think you'll need to add as the last argument to this and the `getPrice` call so they don't throw:
```
{ from: emp.address }
```

This is because these methods are only callable by registered contracts. Conveniently, for view functions, you're allowed to specify any address you want as the `from` address. If you don't do this, I think the function will throw. Because of some weirdness in web3 and some/all node implementations, throws in a view function seem to just resolve to `true` (this is what I saw in my console when testing). See here for more details on this weirdness: https://github.com/ethereum/solidity/issues/4840#issue-352539391.

Comment (mrice32) [reply core/scripts/cli/sponsor/viewLiquidationDetails.js:113]: Just for reference, [here's](https://github.com/UMAprotocol/protocol/blob/29ad088075872e4d24c46cf2dd6dc59b09d3ad0b/core/contracts/oracle/implementation/Voting.sol#L254) the hasPrice() function with the `onlyRegisteredContracts()` modifier.

File: core/scripts/cli/sponsor/viewLiquidationDetails.js (hunk 2 above)
Comment (mrice32) [reply core/scripts/cli/sponsor/viewLiquidationDetails.js:91]: LGTM

File: core/scripts/cli/sponsor/viewLiquidationDetails.js (hunk 3 above)
Comment (nicholaspai) [reply core/scripts/cli/sponsor/viewLiquidationDetails.js]: Got it. Done and added a commend since this is esoteric

File: core/scripts/cli/sponsor/viewLiquidationDetails.js [hunk 4]
```diff
@@ -1,24 +1,151 @@
...
+      const Finder = artifacts.require("Finder");
+      let finder = await Finder.deployed();
+      const OracleInterface = artifacts.require("OracleInterface");
+      let oracle = await OracleInterface.at(
+        await finder.getImplementationAddress(web3.utils.utf8ToHex(interfaceName.Oracle))
+      );
+      // Need to pass {from:emp.address} in this EMP view-only calls because of this web3 view method bug
+      // https://github.com/ethereum/solidity/issues/4840#issue-352539391 that would return true regardless
+      // if the Oracle has actually resolved a price. This is because `hasPrice` and `getPrice` have the
+      // `onlyRegisteredContract` modifier.
```
Comment (mrice32) [inline core/scripts/cli/sponsor/viewLiquidationDetails.js:116]: nit: sorry this is actually a little more convoluted than that. You need to pass `{ from: emp.address }` because the *method will revert*.

The bug only affects what happens if you *don't* do that. One would expect web3 to throw an error, but instead it just returns true. This probably doesn't need to be mentioned in comments explicitly. I only mentioned it earlier as a warning in case you were to test it out.

Sorry if I miscommunicated that.

File: core/scripts/cli/sponsor/viewLiquidationDetails.js [hunk 5]
```diff
@@ -1,24 +1,151 @@
...
+      // a price has not resolved yet, or a price has resolved that indicates that the dispute will FAIL.
+
+      // Fetch oracle price and use it to customize error message.
+      const Finder = artifacts.require("Finder");
+      let finder = await Finder.deployed();
+      const OracleInterface = artifacts.require("OracleInterface");
+      let oracle = await OracleInterface.at(
+        await finder.getImplementationAddress(web3.utils.utf8ToHex(interfaceName.Oracle))
+      );
+      // Need to explicitly pass {from:emp.address} in these EMP view-only calls because they will revert due to their
```
Comment (nicholaspai) [inline core/scripts/cli/sponsor/viewLiquidationDetails.js:113]: @mrice32 Is this comment accurate?

Comment (mrice32) [reply core/scripts/cli/sponsor/viewLiquidationDetails.js:113]: Yep!
