### PR TITLE
Winston twilio transport

### LINKED ISSUE #1097: implement phone calls from slack bot
**Error:** anything that requires human intervention. If the bot is low on funds or a transaction fails (some txn failures are sporadic and normal, but it may be difficult to distinguish). These can trigger every iteration, but only if it's because the bot encounters a persistent issue that requires human intervention to solve. Trigger a DM to oncall, text/call to oncall, and publish to a slack channel that nobody has muted (or just use @channel to force a notif).

### LINKED ISSUE #1100: Link twilio script to winston transport
The current twilio implementation does not link to winston. this needs to be improved.

### PR DESCRIPTION
**Pull request by chrismaree**
This PR creates a winston transport to link into the twilio module defined in the previous PR #1099. For this implementation the twilio bot will call the numbers defined in the env for any `error` level message.

Close #1100 
close #1097

### CODE REVIEW

File: financial-templates-lib/Logger.js [hunk 1]
```diff
@@ -158,6 +160,12 @@ if (process.env.SLACK_WEBHOOK) {
   );
 }
 
+// If all the required environment variables for twilio are added, add the transport
+if (process.env.TWILIO_SID && process.env.TWILIO_AUTH && process.env.DRI_NUMBER1 && process.env.TWILIO_FROM_NUMBER) {
```
Comment (mrice32) [inline financial-templates-lib/Logger.js]: nit: don't we do this same check in the `RoboCaller` class? Just curious if there's a simple way to avoid having to check this in two places?

File: financial-templates-lib/TwilioTransport.js [hunk 2]
```diff
@@ -0,0 +1,15 @@
...
+
+module.exports = class TwilioTransport extends Transport {
+  constructor(opts) {
+    super(opts);
+    this.RoboCaller = new RoboCaller();
+  }
+
+  log(info, callback) {
+    // place the call with the given message.
+    this.RoboCaller.placeCall(`Error reported from ${info.at} with message ${info.message}`);
```
Comment (mrice32) [inline financial-templates-lib/TwilioTransport.js]: Isn't this an async method? If you call it synchronously, won't the async part just be waiting forever until the main thread yields?

File: financial-templates-lib/Logger.js (hunk 1 above)
Comment (nicholaspai) [reply financial-templates-lib/Logger.js]: you could create a separate module, "Transports.js" perhaps, that has a simple getter() which just checks which transports are available depending on which .env variables are filled out correctly.

Comment (nicholaspai) [reply financial-templates-lib/Logger.js]: would have the benefit of isolating all "dotenv" calls to one module

Comment (chrismaree) [reply financial-templates-lib/Logger.js]: I tried to refactor this to have one check in the `RoboCaller` that has a method that can be called but it is inaccessible from within the `Logger.js` because the object has not been initialized as of yet.

File: financial-templates-lib/TwilioTransport.js (hunk 2 above)
Comment (chrismaree) [reply financial-templates-lib/TwilioTransport.js]: ye, this is how it is implemented here. the `placeCall` function returns of hangs within ~1 second but you are right it should deal with the promise more gracefully. I refectored this to by async.

File: financial-templates-lib/Logger.js (hunk 1 above)
Comment (chrismaree) [reply financial-templates-lib/Logger.js]: @nicholaspai this is a good idea. I want to separate that to a different PR though because it will change the slack implementation as well. I created an issue for it: #1106

Comment (mrice32) [reply financial-templates-lib/Logger.js]: Does this mean that you *won't* be checking in the `RoboCaller` class, itself? Would the environment variables be passed from this new module all the way down to the `RoboCaller` class, so it doesn't need to look them up?

Comment (chrismaree) [reply financial-templates-lib/Logger.js]: ye, I think this is what @nicholaspai is suggesting, right?

Comment (mrice32) [reply financial-templates-lib/Logger.js]: SGTM
